### ISSUE TITLE
[主線] [PTT] 實作個人看板的使用者資訊的http套件

### ISSUE THREAD

**Issue by fish-dumpling** [Ptt-official-app/Ptt-backend#100]
### 實作細節 / Details of Implement
#52 的子issue
修改route_users.go 
1. 修改error message
2. 檢查token(再討論要放在usecase還是http)
3. 補齊testcode

### 期程 / Schedule
- 討論時間： 3天
- 實作時間： 1天
- 確認時間： 1天

### 相關文件 / Documents
- 母issue #52
- [PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by y2468101216** [comment]
error code message 要如何修改目前有頭緒了嗎?
檢查 token 要不要作一個 middleware 去處理
test code 已經在 #114 補上了

**Comment by PichuChen** [comment]
> error code message 要如何修改目前有頭緒了嗎?
> 檢查 token 要不要作一個 middleware 去處理
> test code 已經在 #114 補上了

這個是不是回錯邊了？

**Comment by hungyiwu** [comment]
這個有人認領嗎？可以 assign 給我嗎？

**Comment by gogog22510** [comment]
我可以試試看

**Comment by PichuChen** [comment]
> 我可以試試看

感謝，再麻煩你了

**Comment by PichuChen** [comment]
剛剛看了一下，這個ISSUE是在之前 refactor 就已經有實作了嗎？

**Comment by gogog22510** [comment]
對我開始時發現已經有實作了，我就照著issue的1，2，3點做修改test case和log error的部分
