### ISSUE TITLE
[主線] [PTT] 實作熱門文章的 http 套件

### ISSUE THREAD

**Issue by linmeichu** [Ptt-official-app/Ptt-backend#107]
### 實作細節 / Details of Implement
- 參考 https://github.com/Ptt-official-app/Ptt-backend/issues/50 實作熱門文章
- 在 delivery/http/route_popular_articles.go 裡面新增 getPopularArticles 內容參考 getPopularBoardList
- 請推入 feature/popular_articles 的 branch

### 期程 / Schedule
- 討論時間： 一天
- 實作時間： 一天
- 確認時間： 一天

### 相關文件 / Documents
[後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)

**Comment by gn01842919** [comment]
我想試試看

**Comment by linmeichu** [comment]
@gn01842919 
還是你要不要做 repository 部分呢？
https://github.com/Ptt-official-app/Ptt-backend/issues/86

**Comment by gn01842919** [comment]
做好了喔，等待 PR review 中
