### ISSUE TITLE
[主線] [PTT] 實作 我的最愛列表 的測試

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#112]
### 實作細節 / Details of Implement
internal\delivery\http\route_users.go:76 - getUserFavorites
此 route 尚未實作測試

### 期程 / Schedule
- 討論時間：一天
- 實作時間：三天
- 確認時間：一天

### 相關文件 / Documents
可參考 #45 

### 備註
開發前請先參考 FOR_TEST_DEVELOPERS.md 裡的說明

**Comment by DeanXu2357** [comment]
我可以幫忙，請指派給我
