### ISSUE TITLE
[主線] [PTT] 實作文章推文 delivery/http

### ISSUE THREAD

**Issue by DeanXu2357** [Ptt-official-app/Ptt-backend#115]
### 實作細節 / Details of Implement
此為 #68 子任務
主要實作 delivery 內 error & responses ，並完成 testcase 和補充完整 swagger 文件。
實作完成後推至 feature/append_comment

### 期程 / Schedule
- 討論時間： 兩天, 到 3/7 
- 實作時間： 三天, 到 3/10 
- 確認時間： 兩天, 到 3/12 

### 相關文件 / Documents
主任務 #68
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)
[Swagger](https://pttapp.cc/swagger/)

**Comment by DeanXu2357** [comment]
目前 usecase 中有 CheckPermission 方法，請問推文限制是如同其他實作一樣都假裝邏輯寫在該方法內嗎？

**Comment by PichuChen** [comment]
CheckPermission 要送入你想驗證的 Permission
