### ISSUE TITLE
[主線] [PTT] 實作使用者設定 delivery/http

### ISSUE THREAD

**Issue by kyho4515** [Ptt-official-app/Ptt-backend#118]
### 實作細節 / Details of Implement
#62 子issue
實作 delivery內的response及error handling, 並完成test code.
### 期程 / Schedule

- 討論時間： 兩天, ~3/8
- 實作時間： 三天, ~3/11
- 確認時間： 兩天, ~3/13

### 相關文件 / Documents
主issue #62
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)

**Comment by kyho4515** [comment]
@PichuChen 想問一下test code目前只需要把function開好就好嗎?

**Comment by PichuChen** [comment]
> @PichuChen 想問一下test code目前只需要把function開好就好嗎?

test code 的話目前標準是有基本功能就行了

**Comment by hungyiwu** [comment]
[update] 不好意思沒有看到已經有 PR 了 :sweat_smile: 

我想認領這個，謝謝!
