### ISSUE TITLE
[功能] 找尋同標題文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#13]
根據 PTT APP 規劃，後台應該要提供找尋同標題文章的功能

預定透過 /v1/boards/{{board_id}}/articles API 實作

修改 PTT 後端系統協定增加參數 ?title={{search_title_id}} 來完成

初期演算法先以 O(n) 的演算法進行實作即可， n 為某看板文章數量。

**Comment by ars0915** [comment]
可以assign給我嗎?

**Comment by PichuChen** [comment]
@ars0915  所以你那邊目前是一次有兩個ISSUE?

**Comment by ars0915** [comment]
> @ars0915  所以你那邊目前是一次有兩個ISSUE?

是的，因為這兩個功能感覺是在同一支API

**Comment by PichuChen** [comment]
> > @ars0915  所以你那邊目前是一次有兩個ISSUE?
> 
> 是的，因為這兩個功能感覺是在同一支API

了解，因為我很弱的發現還有第三個 ISSUE 可能也是同個修改點，查詢推文XD

**Comment by ars0915** [comment]
> > > @ars0915  所以你那邊目前是一次有兩個ISSUE?
> > 
> > 是的，因為這兩個功能感覺是在同一支API
> 
> 了解，因為我很弱的發現還有第三個 ISSUE 可能也是同個修改點，查詢推文XD

推文數那個嗎xD 本來有想說要不要一起做了

**Comment by PichuChen** [comment]
> > > > @ars0915  所以你那邊目前是一次有兩個ISSUE?
> > > 
> > > 
> > > 是的，因為這兩個功能感覺是在同一支API
> > 
> > 
> > 了解，因為我很弱的發現還有第三個 ISSUE 可能也是同個修改點，查詢推文XD
> 
> 推文數那個嗎xD 本來有想說要不要一起做了

那你就再開一個 ISSUE 一起做好了

**Comment by ars0915** [comment]
> > > > > @ars0915  所以你那邊目前是一次有兩個ISSUE?
> > > > 
> > > > 
> > > > 是的，因為這兩個功能感覺是在同一支API
> > > 
> > > 
> > > 了解，因為我很弱的發現還有第三個 ISSUE 可能也是同個修改點，查詢推文XD
> > 
> > 
> > 推文數那個嗎xD 本來有想說要不要一起做了
> 
> 那你就再開一個 ISSUE 一起做好了

@PichuChen 測試的部份要不要等 #16 merge 後再寫呢?

**Comment by PichuChen** [comment]
@ars0915  可以問一下目前這個 ISSUE 的進度到哪邊了嗎？
