### ISSUE TITLE
[建議] remove sudo command example on README

### ISSUE THREAD

**Issue by RicoToothless** [Ptt-official-app/Ptt-backend#135]
### 原本作法的問題 / Existed Problem

docker-compose example `sudo docker-compose up -d` is not best practice

### 實作細節 / Details of Implement

It should be `docker-compose up -d`

### 期程 / Schedule

- 實作時間：5 mins

### 相關文件 / Documents

[Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)

**Comment by PichuChen** [comment]
他不用 sudo 的話跑得起來嗎？

Ref: https://github.com/Ptt-official-app/Ptt-backend/pull/44#issuecomment-776428153
