### ISSUE TITLE
[主線] [PTT] 實作顯示看板資訊細部資訊的http套件

### ISSUE THREAD

**Issue by nickyanggg** [Ptt-official-app/Ptt-backend#137]
### 實作細節 / Details of Implement

修改 route.go、route_boards.go，並預期能夠從 bbs.BoardRecord 中獲取回傳資料。
由於目前 bbs.BoardRecord 尚無法提供回傳資料，所以暫時先回傳寫死的資料。
### 期程 / Schedule
- 討論時間： 1 天
- 實作時間： 1 天
- 確認時間： 1 天

### 相關文件 / Documents

- 母 issue：#65
- [PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.qiotemweyhbo)

**Comment by PichuChen** [comment]
@nickyanggg 可以確認一下這個 ISSUE 目前的狀態嗎？

**Comment by nickyanggg** [comment]
> @nickyanggg 可以確認一下這個 ISSUE 目前的狀態嗎？

#138 
目前已經照 reviewer 提供的意見修改完畢，正等待被重新 review。
