### ISSUE TITLE
[功能] 找同作者文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#14]
根據 PTT APP 規劃，後台應該要提供找尋同樣作者的功能

預定透過 /v1/boards/{{board_id}}/articles API 實作

修改 PTT 後端系統協定增加參數 ?author={{search_author_id}} 來完成

初期演算法先以 O(n) 的演算法進行實作即可， n 為某看板文章數量。

**Comment by ars0915** [comment]
可以assign給我嗎?

**Comment by PichuChen** [comment]
@ars0915  可以問一下目前這個 ISSUE 的進度到哪邊了嗎？

**Comment by ars0915** [comment]
> @ars0915 可以問一下目前這個 ISSUE 的進度到哪邊了嗎？

這個和 #13 #26 的進度一樣，都在 #24 這個 PR 上，目前測試也寫了，剩調整一下 mock 檔案的位置。
