### ISSUE TITLE
[建議] API 文件增加 HTTP Status Code

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#145]
### 原本作法的問題 / Existed Problem
目前的 API 文件沒有詳細列出各種 Status Code 以及各種錯誤時回傳的 Status Code
這樣在實作 delivery 時會比較有模糊的空間，對前端也不好做錯誤處理

### 實作細節 / Details of Implement
1. 在 API 文件上新增 Status Code
2. 更新 Swagger 文件
3. 立 issue 修改現有 delivery 實作不符的地方

### 期程 / Schedule
- 討論時間： 一週
- 實作時間： 待確認
- 確認時間： 待確認

### 相關文件 / Documents
[API 文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.xtgbc6lc04uw)

**Comment by PichuChen** [comment]
目前的 status code 的政策是 2 3 4 5 而已，假如是Client錯誤回應 4開頭的 Server 錯誤回應 5 開頭的。
然後在錯誤的時候會有 error 和 error_description 兩個欄位， error_description 建議是可以直接顯示在最前端，讓 Enduser 可以截圖回報錯誤，方便 Debug 使用的，那細節來說我認為應該要去設計 error 的 name space，目前在各大廠的錯誤處理似乎沒有一個比較通用的設計也是一個問題。

在錯誤處理的設計原則上，我會假定以下狀況：
* Client 或是前端並不會認真進行錯誤處理，
* 設計期沒辦法預測所有可能的錯誤，錯誤的種類必然會在未來增加
* 錯誤有可能發生在我們可以處理或是我們不能處理的地方，例如硬碟空間已滿
* 清楚的錯誤訊息可以加快錯誤的解決時間，但是太複雜的訊息對使用者而言有點可怕，但是如果只是一句「伺服器錯誤」對於除錯而言幫助很低，如果是把實際伺服器的 exception 資訊整個送往前端又太多了，因此要在這之間有個取捨
* End User 不一定會回報所有錯誤，因此在維運上也需要統計發生錯誤的狀況
* 在錯誤處理中如果可以增加「應該如何修正」的提示的話對於開發效率會有很大的幫助，「缺少 action 參數」這樣的錯誤訊息回比「缺少參數」還要有意義

大概是這樣

**Comment by wagaru** [comment]
以 MileStone 1 的目地是要讓前端能夠快樂開發的話，現階段或許可以先不用考慮 End User，只考慮前端？
但前端對錯誤處理的態度我就不確定了 XD

不過現階段是可以將錯誤訊息包一個 helper 出來做集中處理，裡面定義 error_code 與 error_description 之類的
當要回傳錯誤給前端時比較有一致的寫法(詳細做法可以再討論)
這樣的話，或許 API 文件跟 Swagger 可以之後比較明確時再補充就好~

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？

**Comment by joremysh** [comment]
看了目前後端的程式碼裡面有好幾個 API 在 swagger.yaml 都沒有，我來幫忙加上吧？

1. /v1/users/{user_id}/ - articles, preferences 等等
2. popular-boards
3. popular-articles
4. classes

**Comment by PichuChen** [comment]
> 看了目前後端的程式碼裡面有好幾個 API 在 swagger.yaml 都沒有，我來幫忙加上吧？
> 
> 
> 
> 1. /v1/users/{user_id}/ - articles, preferences 等等
> 
> 2. popular-boards
> 
> 3. popular-articles
> 
> 4. classes

歡迎👏

好了可以送PR上來之後Tag這個ISSUE,或是開一個tag這個ISSUE的ISSUE後講PR tag 該ISSUE
