### ISSUE TITLE
[主線] [PTT] 實作推文 usecase 

### ISSUE THREAD

**Issue by DeanXu2357** [Ptt-official-app/Ptt-backend#147]
### 實作細節 / Details of Implement
完成推文功能的 usecase ，尚未定義的地方已註解標記
實作完成後推至 feature/append_comment

### 期程 / Schedule
- 討論時間：
- 實作時間： 到 3/23
- 確認時間： 到 3/27

### 相關文件 / Documents
主任務 #68
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)
[Swagger](https://pttapp.cc/swagger/)

**Comment by PichuChen** [comment]
可以把 usecase 和 repository 分開嗎？

**Comment by DeanXu2357** [comment]
好，這個issue我先做 usecase

**Comment by PichuChen** [comment]
@DeanXu2357 可以問一下目前這個 ISSUE 的狀態嗎？

**Comment by DeanXu2357** [comment]
抱歉前幾天再忙還沒寫，今天晚點會推 pr
