### ISSUE TITLE
[主線] [PTT] 實作使用者設定 -- 修改usecase和repository

### ISSUE THREAD

**Issue by kyho4515** [Ptt-official-app/Ptt-backend#148]
### 實作細節 / Details of Implement
- 修改 internal/usecase/user.go
  - 修改GetUserPreferences內的data
- 修改 internal/repsitory/user.go
  - 新增dummy function給usecase

### 期程 / Schedule
- 討論時間： 兩天, 到 3/25
- 實作時間： 兩天, 到 3/27
- 確認時間： 兩天, 到 3/29

### 相關文件 / Documents
主issue: #62 
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by kyho4515** [comment]
想確認一下repository的寫法, 因為go-bbs還沒有相對應的method, 目前這部分是直接對每個usecase裡的field都建一個dummy function嗎?

**Comment by PichuChen** [comment]
> 想確認一下repository的寫法, 因為go-bbs還沒有相對應的method, 目前這部分是直接對每個usecase裡的field都建一個dummy function嗎?

對

**Comment by PichuChen** [comment]
@kyho4515 可以問一下目前這個 ISSUE 的狀態嗎？

**Comment by kyho4515** [comment]
> @kyho4515 可以問一下目前這個 ISSUE 的狀態嗎？

這幾天比較忙一點, 這部分已經改好, 準備送出pull request了
