### ISSUE TITLE
[主線] [PTT] 將 readme.md 調整對開發者更易上手的格式

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#151]
### 實作細節 / Details of Implement
目前的話，readme.md 皆是以歷史背景出發點再說的。
開發者對於如何參與這個專案是一頭霧水的。

目前我個人看法是應該直接把 milestone 擺在顯眼的地方，並且每個 isssue 都應該要確實的 assign 給某個要接的人。
避免出現明明這個 issue 有人再做卻要看討論才知道。

然後應該要把時程表放在顯眼的地方，哪邊做了哪邊沒做，方便開發者知道目前進度。

### 期程 / Schedule
無，討論到大家滿意為止

### 相關文件 / Documents
README.md

**Comment by PichuChen** [comment]
時程表的部分應該會放在 FOR_DEVELOPER.md 上面，因為開發者和實際上執行使用的人是兩種使用者
