### ISSUE TITLE
[主線] [PTT] 實作轉錄看板文章 -- delivery/http

### ISSUE THREAD

**Issue by arhtur007** [Ptt-official-app/Ptt-backend#152]
### 實作細節 / Details of Implement
* 此為 #66 子任務
* 實作 [http.go](https://github.com/Ptt-official-app/Ptt-backend/blob/c7963687ce513557459c87198f207e4dc0999275/internal/delivery/http/http.go)
* 實作初步的 http_test.go
### 期程 / Schedule
* 討論時間： 一週, 到 4/7
* 實作時間：一週, 到 4/14
* 確認時間：一週, 到 4/21

### 相關文件 / Documents
* 主issue: #66  
* [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit)

**Comment by PichuChen** [comment]
@arhtur007 可以幫我補充一下大致上會修改的檔案的檔案位置嗎？

**Comment by titaneric** [comment]
嗨，我可以負責做這個，可能4/9開始做，一週到4/16截止

**Comment by PichuChen** [comment]
> 嗨，我可以負責做這個，可能4/9開始做，一週到4/16截止

十分感謝！
