### ISSUE TITLE
[主線] [PTT] 實作轉錄看板文章 -- usecase

### ISSUE THREAD

**Issue by arhtur007** [Ptt-official-app/Ptt-backend#153]
### 實作細節 / Details of Implement
* 此為 #66 子任務
* 在 [usecase.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/usecase.go#L63) 實作
  * 檢查目前使用者有沒有在該版發文權限
  * 檢查轉錄文章相關權限
### 期程 / Schedule
* 討論時間： 一週, 到 4/7
* 實作時間：一週, 到 4/14
* 確認時間：一週, 到 4/21

### 相關文件 / Documents
* 主issue: #66  
* [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit)

**Comment by PichuChen** [comment]
@arhtur007 可以幫我補充一下大致上會修改的檔案的檔案位置嗎？

**Comment by arhtur007** [comment]
這個請讓我試試

**Comment by PichuChen** [comment]
@arhtur007  想確定一下目前這個 ISSUE 的進度到哪邊了？

**Comment by RicoToothless** [comment]
我願意試試看這個

**Comment by PichuChen** [comment]
轉錄文章的相關程式邏輯在 pttbbs 的 bbs.c 的 cross_post
https://github.com/ptt/pttbbs/blob/e5668c1e184da082cf28184ec29154e6c2ab4263/mbbsd/bbs.c#L2055

**Comment by PichuChen** [comment]
@RicoToothless 想問一下目前進度到哪邊了？

**Comment by RicoToothless** [comment]
學 C 去設法看懂你貼的 code
