### ISSUE TITLE
[主線] [PTT] 實作轉錄看板文章 -- repository

### ISSUE THREAD

**Issue by arhtur007** [Ptt-official-app/Ptt-backend#154]
### 實作細節 / Details of Implement
* 此為 #66 子任務
* 實作 [repository.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/repository.go)
* 因為 [go-bbs](https://github.com/Ptt-official-app/go-bbs) 尚未完成，需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。
### 期程 / Schedule
* 討論時間： 一週, 到 4/7
* 實作時間：一週, 到 4/14
* 確認時間：一週, 到 4/21

### 相關文件 / Documents
* 主issue: #66  
* [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit)

**Comment by PichuChen** [comment]
@arhtur007 可以幫我補充一下大致上會修改的檔案的檔案位置嗎？

**Comment by RicoToothless** [comment]
我願意試試看這個 issue

**Comment by PichuChen** [comment]
> 我願意試試看這個 issue

再麻煩你了
