### ISSUE TITLE
[主線] [PTT] 實作轉錄信箱 http module

### ISSUE THREAD

**Issue by titaneric** [Ptt-official-app/Ptt-backend#155]
## 實作細節 / Details of Implement

此為 #67 子任務
 http 部分請依照文件實作並且有初步的 testcode。

## 期程 / Schedule

討論時間： 一週, 到 4/7
實作時間：一週, 到 4/14
確認時間：一週, 到 4/21

## 預期修改檔案

- delivery/http下新增類似route_forward_article.go並按照文件實作
- delivery/http/route.go的postBoards method 需要針對action = "forward_article"做處理，並引用route_forward_article.go實作的method
- 補上對應測試

## 相關文件 / Documents

#67 
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx)

**Comment by PichuChen** [comment]
@titaneric 可以幫我補一下大致上會需要修改的檔案的檔案位置嗎？

**Comment by AmberFu** [comment]
我會試著實作這部分

**Comment by PichuChen** [comment]
@AmberFu 目前實作上有遇到問題嗎？

**Comment by AmberFu** [comment]
@titaneric 好像幫我做掉了，我現在幫忙 review code 而已。

**Comment by PichuChen** [comment]
在 #152 實作掉了，所以 Close
