### ISSUE TITLE
[主線] [PTT] 實作轉錄信箱 usecase module

### ISSUE THREAD

**Issue by titaneric** [Ptt-official-app/Ptt-backend#156]
## 實作細節 / Details of Implement

此為 #67 子任務
usecase 部分應該要檢查目前使用者有沒有轉錄信箱相關權限。

## 期程 / Schedule

討論時間： 一週, 到 4/7
實作時間：一週, 到 4/14
確認時間：一週, 到 4/21

## 預期修改檔案

usecase下的article.go新增forwardArticle method
usecase/usecase.go中的interface須新增`forwardArticle` method到usecase interface
檢查權限及補上對應測試

## 相關文件 / Documents

#67 
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx)

**Comment by PichuChen** [comment]
@titaneric 可以幫我補一下大致上會需要修改的檔案的檔案位置嗎？

**Comment by PichuChen** [comment]
related to #153

**Comment by PichuChen** [comment]
在轉錄信箱的 usecase 當中，可能要增加新的設定值，讓系統站長可以設定使用寄信的 API, 類似 Provider 這樣？

**Comment by wagaru** [comment]
> 在轉錄信箱的 usecase 當中，可能要增加新的設定值，讓系統站長可以設定使用寄信的 API, 類似 Provider 這樣？

那想確定一下，這張卡也包含至少實作一種發信方式嗎？

**Comment by PichuChen** [comment]
他應該去串接 provider 的 interface 就行了，所以可能是一個 method 他裡面有三個參數 `to string, title string, body string` 這樣

**Comment by wagaru** [comment]
剛試了一下，取得單篇文章 /v1/boards/{{board_id}}/articles/{{filename}} 目前只有回傳 raw，沒有 parsed，換言之現在無法單獨取得某篇文章的標題跟內文，也就是發信的 title 跟 body。

**Comment by PichuChen** [comment]
> 剛試了一下，取得單篇文章 /v1/boards/{{board_id}}/articles/{{filename}} 目前只有回傳 raw，沒有 parsed，換言之現在無法單獨取得某篇文章的標題跟內文，也就是發信的 title 跟 body。

對，parse 應該會在 Ptt-backend 這邊做？

**Comment by PichuChen** [comment]
title 的部分可以從文章列表的部分取得 title，body 的部分可以整組送進去，唯一的問題大概是有沒有要去掉色碼和轉 UTF-8
