### ISSUE TITLE
[主線] [PTT] 實作轉錄信箱 repository module

### ISSUE THREAD

**Issue by titaneric** [Ptt-official-app/Ptt-backend#157]
## 實作細節 / Details of Implement

此為 #67 子任務
repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。

## 預期修改位置

初步看起來可以直接沿用repository/board.go下的GetBoardArticle，應該可以不用新增

## 期程 / Schedule

討論時間： 一週, 到 4/7
實作時間：一週, 到 4/14
確認時間：一週, 到 4/21

## 相關文件 / Documents

#67 
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx)

**Comment by PichuChen** [comment]
@titaneric 可以幫我補一下大致上會需要修改的檔案的檔案位置嗎？

**Comment by water25234** [comment]
請問這有人接手嗎？
我可以先試這issue

**Comment by PichuChen** [comment]
再麻煩你了

**Comment by water25234** [comment]
已開發 https://github.com/Ptt-official-app/Ptt-backend/pull/189/files
