### ISSUE TITLE
Clean Architecture

### ISSUE THREAD

**Issue by mkfsn** [Ptt-official-app/Ptt-backend#16]
嗨大家好，為了寫出更健全的系統，我想導入 Clean Architecture 到這個專案。

跟 @PichuChen 討論過後，覺得最好還是讓每個人都可以參與，所以決定開個 issue 來 ~讓大家鞭~ 跟大家一起討論，我會盡我所能的解釋我想做的，如果有描述不清楚的還請見諒，也歡迎指出你覺得不妥的地方，甚至更歡迎提供更好的做法，目標是能夠寫出更好的系統，也有助於自我學習，感謝！

回到正題，關於 Clean Architecture，我是參考這幾篇文章：
- [Trying Clean Architecture on Golang](https://medium.com/hackernoon/golang-clean-archithecture-efd6d7c43047)
- [DAY8 - 讓你的 Backend 萬物皆虛，萬事皆可測 - Clean Architecture 測試篇](https://ithelp.ithome.com.tw/articles/10241698)

現在的 code 我看到的問題有幾個：
1. 不好寫 Unit test，因為所有的東西都在 main （不過個人淺見，嚴格上來說這跟 Clean Architecture 比較無關）
2. 沒有抽象的概念。以 #7 為例，假設之後要把 build-in 的 http 換成 mux/gin 等等的話，勢必是大改，改完會不會跟預期的行為一致也是另一個問題。

為了讓系統有較高的彈性，方便抽換第三方套件，我覺得套用 Clean Architecture 不失為一個好的選擇。

那麼實際上會怎麼做呢？這邊先提供一下我自己切完三個 layer 之後的結果：

```
.
├── cmd
│   ├── cmd
│   └── main.go
└── internal
    ├── config
    │   └── config.go
    ├── delivery
    │   └── http
    │       ├── http.go
    │       ├── route.go
    │       ├── route_boards.go
    │       ├── route_boards_treasures.go
    │       ├── route_borads_articles.go
    │       ├── route_classes.go
    │       ├── route_token.go
    │       ├── route_users.go
    │       └── route_users_test.go
    ├── logging
    │   └── logger.go
    ├── repository
    │   ├── board.go
    │   ├── repository.go
    │   └── user.go
    └── usecase
        ├── board.go
        ├── token.go
        ├── usecase.go
        └── user.go
```

首先，我把整個專案切了三層： `delivery`, `usecase`, `repository`，讓我逐一介紹每一層的分工。

在 `delivery` 這一層，主要是做 API 的接口。例如我們現在是用 http ，所以這一層就會專門處理像是 http 的 routing (parsing) 還有從 http request 抽出需要的資料（例如： http header 中的 token ）。未來，這一層可能會被換成使用 mux/gin 也說不定。也說不定我們會要提供 gRPC, GraphQL ，但我相信把我們的商業邏輯抽出來之後，這一層的修改應該不會太大。

在來是 `usecase` 這一層，主要是處理我們的商業邏輯。講得白話一點，今天如果看到一個 API 是 GET /user/info 的話，在 usecase 這一層理論上就會有一個 function/method 在處理 /user/info。因為我們把商業邏輯抽出來了，代表我們不去依賴像是 [http.Request](https://golang.org/pkg/net/http/#Request), [http.ResponseWriter](https://golang.org/pkg/net/http/#ResponseWriter)，這樣也有利於我們寫 Unit test。

最後是 `repository` 這一層，這一層不外乎是處理 DB 或者以我們的 case 的話，目前是依賴 "github.com/PichuChen/go-bbs" 這個第三方套件。之前也有討論過要不要把 ptt 轉成使用 RDBMS，雖然近期內應該是很難，但是切了這層也保證了 DB layer 的彈性，也方便我們之後要換掉 library 。

> 對於看到中英文混雜想吐槽的人，請容我先說聲抱歉 ... 小弟中文不好 😅 請多多包容

小弟對於自己的描述沒有信心，所以如果需要直接看 code 的話，請看： https://github.com/mkfsn/Ptt-backend/tree/feat/clean-architecture 。這邊也要先做個聲明，我有盡可能不動到原本的邏輯，如果您有看到任何不懂或是不妥的地方也請不吝指出。關於 naming 不妥的地方，那純粹是小弟英文不好 😓 也請多多包涵！至於一些 coding stlye 的問題我想應該是可以暫時忽略，等之後有訂 linting rule 再來修改應該也不算太遲？

> 特別提一下，在 #3 中也有討論到一些架構上的問題，但是 #3 主要還是要去 follow go-standard 的結構，跟 Clean Architecture 所要做的事情還是有所差異。

因為這是一個 Open Source 的專案，所以我想不是由我一個，或是少數幾個人就決定方向的，因此如果大家覺得現在的架構也可以寫得輕鬆自在，也歡迎提出意見。我想最重要的還是參與，還有能不能從中學習到東西。

值得一提的是，我覺得要訂架構現在是個不錯的時間點。之後功能越加越多，跟依賴的套件耦合度只會越來越高，那到時候只會趨向懶得切，最後就是一團 legacy code 想動都動不了 XD 

---

最後還是重複一次，小弟也還在學習中，不是說上述這個架構就是最好的，只是因為我看到一些問題，然後以我目前的經驗 Clean Architecture 不失為一個解法，想藉由這個 issue 拋磚引玉，請大家鞭小力一點 ... 🙇🏻

> 也感謝您努力讀完這一長篇內容 XDDD

**Comment by PichuChen** [comment]
s/RMDB/RDB/ or RDBMS?

**Comment by mkfsn** [comment]
> s/RMDB/RDB/ or RDBMS?

@PichuChen  感謝，已修正！

**Comment by PichuChen** [comment]
按照這個做法的話，假如要新增水球功能的話，那應該是 `usecase`, `repository`, `http` 各要新增一個檔案了？

**Comment by mkfsn** [comment]
> 按照這個做法的話，假如要新增水球功能的話，那應該是 `usecase`, `repository`, `http` 各要新增一個檔案了？

@PichuChen 不一定會需要新增檔案，不過你的意思應該是三個 layer 都會動到？如果是這個問題的話，我想答案是肯定的，有很大的機會需要三個 layer 都改沒有錯。

**Comment by Julian-Chu** [comment]
還可加上pkg/module切分 ，模組+分層，但對初期專案可能有點overdesign了
```
├── cmd
│   ├── cmd
│   └── main.go
└── internal
    ├── boards
    │    ├──delivery
    │    │     └── http
    │    │       ├── boards_handler.go
    │    │       └── boards_handler_test.go
    │    ├── usecase
    │    │      ├── board.go  
    │    │      └── board_test.go 
    │    │	
    │    └── repository
    │            └── go-bbs
    │                 ├── repository.go
    │                 └── repository_test.go	
    │
    ├──token...
    ├──classes...
```

**Comment by Julian-Chu** [comment]
我個人覺得 @mkfsn 的分法是ok的，依賴的方向性應該不會有問題
只要 @PichuChen 覺得這種分法方便分配工作那就可以考慮先用了， 有需要在邊做邊調整~

**Comment by Markogoodman** [comment]
覺得分層很棒 會好維護很多
發個問

1. logger
logger在每個usecase中和httpDelivery都有一個，或許可以留一個讓大家都可以用就好?
因為 logger 跟 db 不一樣，是個只寫不讀的東西，所以應該不會有大家互相牽制的問題XD 或著是多個logger有特別的用意嗎

2. 命名問題
func (delivery *httpDelivery) 
receiver 需要重新命名嗎，因為之後有可能會有graphqlDelivery之類的，現在叫delivery之後可能會不知道叫啥

3.  repo和usecase
想問的是 user usecase 這邊的邏輯，基本上都不會使用到 board 那邊的資料嗎
舉個例子 userUsecase struct 裡面包了 repository.UserRepository 可以存取 user 的資料，但就碰不到 board 那邊了
或許有個API會想要讀一些user和一些board的資料組合起來傳給client?

最後我也覺得這個pr可以趕快merge XDD
要改東西會很好改

**Comment by hxrgjo** [comment]
看起來不錯，不過有個疑問
internal 這個資料夾感覺沒有太大用處，一定需要它嗎?

**Comment by mkfsn** [comment]
> 還可加上pkg/module切分 ，模組+分層，但對初期專案可能有點overdesign了
> 
> ```
> ├── cmd
> │   ├── cmd
> │   └── main.go
> └── internal
>     ├── boards
>     │    ├──delivery
>     │    │     └── http
>     │    │       ├── boards_handler.go
>     │    │       └── boards_handler_test.go
>     │    ├── usecase
>     │    │      ├── board.go  
>     │    │      └── board_test.go 
>     │    │	
>     │    └── repository
>     │            └── go-bbs
>     │                 ├── repository.go
>     │                 └── repository_test.go	
>     │
>     ├──token...
>     ├──classes...
> ```

@Julian-Chu  感謝意見！我覺得分模組更好！😄 不過也因為先前有跟 @PichuChen 討論到，盡量不要一下子提高門檻，造成有更多人要維護的時候學習成本太高，所以砍了一砍就是我上面提出的架構 XD 但我覺得這個是可以再提出來討論的！


---


@Markogoodman 感謝意見跟提問～讓我逐一回答您的問題 :)

> 1. logger
>    logger在每個usecase中和httpDelivery都有一個，或許可以留一個讓大家都可以用就好?
>    因為 logger 跟 db 不一樣，是個只寫不讀的東西，所以應該不會有大家互相牽制的問題XD 或著是多個logger有特別的用意嗎

這個問題在這邊有被提過一次：
https://github.com/Ptt-official-app/Ptt-backend/issues/3#issuecomment-763712256
https://github.com/Ptt-official-app/Ptt-backend/issues/3#issuecomment-763717065

因為沒有結論所以就先暫時擱著，現在放多個 logger 的主要原因是改動比較不會那麼大，至少不用一直把同一個 logger 傳來傳去這樣，但我對這個的解法也沒有特別覺得怎麼做比較好，所以可以再討論！希望沒有讓你很 confused XD

> 2. 命名問題
>    func (delivery *httpDelivery)
>    receiver 需要重新命名嗎，因為之後有可能會有graphqlDelivery之類的，現在叫delivery之後可能會不知道叫啥

naming 一直都是個問題 XDD 有人可能會發現我的 code 已經有不 consistent 的地方 😅 像是 usecase 裡面的 receiver 都是單一個字母，然而您提的地方卻是一個字詞 Orz 所以我覺得可以改沒問題唷～

> 3. repo和usecase
>    想問的是 user usecase 這邊的邏輯，基本上都不會使用到 board 那邊的資料嗎
>    舉個例子 userUsecase struct 裡面包了 repository.UserRepository 可以存取 user 的資料，但就碰不到 board 那邊了
>    或許有個API會想要讀一些user和一些board的資料組合起來傳給client?

如果是您提到的這個 case 的話，我目前的解法會是把 boardRepository 也傳給 userUsecase，代表在我們的商業邏輯上，跟 userUsecase 有關的商業邏輯是需要用到 boardRepository 的（有相依性的意思）。個人淺見，我也想知道有沒有更好的做法～



---


> 看起來不錯，不過有個疑問
> internal 這個資料夾感覺沒有太大用處，一定需要它嗎?


@hxrgjo 哈囉，感謝意見～不好意思讓你很 confused 😅 internal 的概念是從這邊來的：

https://github.com/golang-standards/project-layout

在 https://github.com/Ptt-official-app/Ptt-backend/issues/3#issuecomment-763732387 也有提到 internal package 是有特殊意義的，讓其他外部的 project 試圖要 import 這個專案的時候沒辦法 import internal 底下的東西，所以在 #3 我才會提出把東西搬到 internal 底下，不過如果這樣造成大家的困惑的話，我覺得是可以改的～

---

如果我有任何描述不清楚的地方還請見諒，也請不吝指出我講錯的地方 🙇🏻

**Comment by ars0915** [comment]
覺得 @mkfsn 的分層很棒，在 repository 和 usecase 的分層明確可以減少很多維護成本。
對於 logger 我個人的想法是可以像是 helper 的用法讓所有 package 共用，不過這樣就會像 [#3 (comment)](https://github.com/Ptt-official-app/Ptt-backend/issues/3#issuecomment-763712256) 的疑問一樣。

**Comment by PichuChen** [comment]
看起來 logger 的部分有兩種做法：
* 一種是在每個需要的檔案都 import 一次。
* 另外一種是在每個 package 裡面都 new 一次。

以記憶體使用而言，在 Logger 裡面沒有存放東西的前提下應該是相等（都是零）。
以維護的複雜度而言，其實後面修改 internal logger 裡的東西就行了。

所以兩種做法看起來沒有顯著的優劣，因此這部分我建議先暫停討論，以 @mkfsn 現行規劃為主來進行這次修改的討論。

日後如果確定將 @mkfsn 的 layout 作法合併進來後還感覺到有不足的地方時再繼續進行討論。

**Comment by Markogoodman** [comment]
原來logger有其他地方了 那就先不再這邊討論XD

 
> >repo和usecase
> >    想問的是 user usecase 這邊的邏輯，基本上都不會使用到 board 那邊的資料嗎
> >    舉個例子 userUsecase struct 裡面包了 repository.UserRepository 可以存取 user 的資料，但就碰不到 board 那邊了
> >    或許有個API會想要讀一些user和一些board的資料組合起來傳給client?
> 
> 如果是您提到的這個 case 的話，我目前的解法會是把 boardRepository 也傳給 userUsecase，代表在我們的商業邏輯上，跟 userUsecase 有關的商業邏輯是需要用到 boardRepository 的（有相依性的意思）。個人淺見，我也想知道有沒有更好的做法～

我覺得這樣解法OK~

我之前分層的方法就是只有各大層而已，
例如就只有一個
type UseCase struct{
    repo  Repository
}  
然後在 UseCase 和 Repository 上面實作所有的 method
這樣是不用分太細，不過我們那時沒有用interface 測試都是直接用DB
現在這樣interface分細一點可能unit test會比較好寫 (嗎

**Comment by ars0915** [comment]
> 我之前分層的方法就是只有各大層而已，
> 例如就只有一個
> type UseCase struct{
>     repo  Repository
> }  
> 然後在 UseCase 和 Repository 上面實作所有的 method
> 這樣是不用分太細，不過我們那時沒有用interface 測試都是直接用DB
> 現在這樣interface分細一點可能unit test會比較好寫 (嗎
> 
我的理解是，各層都會依照對應的職責去切分 struct，就算不是用 interface 也是會有多個 repository 和 usecase，這種做法在程式的維護性和可讀性是比較高的。
至於分細一點會不會比較好寫 unit test ，這點我覺得不一定，可能要看大家對於好寫的定義，例如有些人可能覺得一個 usecase 的 unit test 需要去 mock 不只一個 repository 很麻煩等等。
我個人是比較傾向於依職責分細一點。

**Comment by mkfsn** [comment]
> 我之前分層的方法就是只有各大層而已，
> 
> 例如就只有一個
> 
> type UseCase struct{
> 
>     repo  Repository
> 
> }  
> 
> 然後在 UseCase 和 Repository 上面實作所有的 method
> 
> 這樣是不用分太細，不過我們那時沒有用interface 測試都是直接用DB
> 
> 現在這樣interface分細一點可能unit test會比較好寫 (嗎
> 

@Markogoodman 感謝～我覺得這個主意不錯耶！這個好像比較簡單一點。

我之所以會那樣分是因為我的經驗上，repository 可能會有連到不同的 DB 。例如某個 repository 是用 MongoDB ，另外一個則是用 MySQL 這樣。但我覺得如果要降低門檻讓更多人可以參與的話，的確是一開始不用設計的那麼複雜。以我們的 case 我猜 DB 只會有一種？然後應該不會有不同的 delivery layer 使用不同的 usecase 吧？如果有錯再煩請指出～

我想只要 interface 有訂好，應該之後要再切成不同的 repository 也不難才對！就看其他人有什麼意見囉？

**Comment by PichuChen** [comment]
如果目前沒有其他反對意見的話，那就看誰要認領這個 ISSUE 進行實作了。

**Comment by Markogoodman** [comment]
> 如果目前沒有其他反對意見的話，那就看誰要認領這個 ISSUE 進行實作了。

問個 
實作是指把 @mkfsn 做的  https://github.com/mkfsn/Ptt-backend/tree/feat/clean-architecture
再修成上面說的只有一個usecase和repository嗎
我可以做~

**Comment by PichuChen** [comment]
@Markogoodman  真是一個出奇不意的認領 ISSUE，基本上是這樣，那就交給你了。

**Comment by Min-Feng** [comment]
@Markogoodman 
@mkfsn

我感覺少了一層 entity 或是 ddd 的 domain 層
domain 層是主要邏輯 的撰寫處
讓相關物件的 method 有對應的邏輯
把業務邏輯 與 持久化的責任分離, 也避免依賴 io 更好執行單元測試

usecase 是
調用 domain 層 與外部 io 溝通的地方

repository 實現 domain 層的 相關抽象

> 然後在 UseCase 和 Repository 上面實作所有的 method
不確定你說這句話的意思
感覺會有貧血模型的問題
因為沒看到 domain 層的出現

**Comment by itsarbit** [comment]
整體看起來還不錯 目前有些nit pick想提出來 不過可以由實作的人決定
1. `delivery` 的層級 最好實作`delivery.go` with an interface 確保之後換成gin的時候可以更快的plug and play.
2. 將不是在`internal` `cmd` 下面的package移動到`pkg` layer作為共用的package layer.
3. 類似第一點任何package都要實作`package.go`作為interface layer and `doc.go` 來做package的說明

**Comment by KScaesar** [comment]
> 整體看起來還不錯 目前有些nit pick想提出來 不過可以由實作的人決定
> 
> 1. `delivery` 的層級 最好實作`delivery.go` with an interface 確保之後換成gin的時候可以更快的plug and play.
> 2. 將不是在`internal` `cmd` 下面的package移動到`pkg` layer作為共用的package layer.
> 3. 類似第一點任何package都要實作`package.go`作為interface layer and `doc.go` 來做package的說明

驅動(http)層
其實已經很薄 沒做什麼事情
只呼叫 用例層, 拿到 回傳值
再寫入到 http 的 response
我覺得 介面 可以只定義在 domain(entity) 和 usecase 層就好

http 即使定義了介面
似乎對 單元測試 的幫助也不會太多
只能測試是否 寫入的 view model 格式 符合預期
這部份注入 mock.usecase 就可以作到

參考文章
[再談Clean Architecture三原則](http://teddy-chen-tw.blogspot.com/2020/08/clean-architecture.html)

>Interface Adapters層經常與框架緊密相關，例如Web Controller和所使用的Web Container框架緊密相關。在這種情況下，要做的完全的依賴反轉是很痛苦的一件事。所以Interface Adapters層放生，就讓它和框架緊密耦合吧。

**Comment by Markogoodman** [comment]
再麻煩大家幫看了 https://github.com/Ptt-official-app/Ptt-backend/pull/23

**Comment by Julian-Chu** [comment]
> 再麻煩大家幫看了 #23

另外有兩點看了code以後覺得可以討論一下
DB interface需要獨立出來一個pkg嗎， 看起來比較偏向是repo內部需要的interface，目前只有mock跟repo會需要它，但是mock DB也是為了repo，可以考慮移進去repo

另外是httpDelivery的命名不太常見, 也許用App/Api/Service ..etc.會比較符合一般的習慣

**Comment by PichuChen** [comment]
> > 再麻煩大家幫看了 #23
> 
> 另外有兩點看了code以後覺得可以討論一下
> DB interface需要獨立出來一個pkg嗎， 看起來比較偏向是repo內部需要的interface，目前只有mock跟repo會需要它，但是mock DB也是為了repo，可以考慮移進去repo
> 
> 另外是httpDelivery的命名不太常見, 也許用App/Api/Service ..etc.會比較符合一般的習慣

稍微有點聽不懂，有 tree 提供參考嗎？

**Comment by Julian-Chu** [comment]
> 
> 稍微有點聽不懂，有 tree 提供參考嗎？
```
├── cmd
│   └── main.go
└── internal
    ├── config
    ├── db
    │    └── db.go
    ├── delivery/http
    ├── logging
    ├── mock
    ├── repository
    └── usecase
```
PR的結構如上圖(比起 @mkfsn 的多了db跟mock)，我想討論的是獨立出一個db package看起來不是必要
https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/db/db.go
db.go 裡面只有含一個DB interface，但是依賴這個interface的只有repo跟mock，所以看起來這個pkg可以拿掉，把DB interface移入repo

另一個是delivery層的 type httpDelivery struct 
https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/delivery/http/http.go#L11
因為我在main.go看到httpDelivery.Run()，覺得httpDelivery不是一般慣用的命名，app.Run()/apiService.Run()/ etc.. 也許比較直觀

**Comment by PichuChen** [comment]
@Julian-Chu @Markogoodman 的確那個 db.go 看起來是不需要

**Comment by Markogoodman** [comment]
> > 稍微有點聽不懂，有 tree 提供參考嗎？
> 
> ```
> ├── cmd
> │   └── main.go
> └── internal
>     ├── config
>     ├── db
>     │    └── db.go
>     ├── delivery/http
>     ├── logging
>     ├── mock
>     ├── repository
>     └── usecase
> ```
> 
> PR的結構如上圖(比起 @mkfsn 的多了db跟mock)，我想討論的是獨立出一個db package看起來不是必要
> https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/db/db.go
> db.go 裡面只有含一個DB interface，但是依賴這個interface的只有repo跟mock，所以看起來這個pkg可以拿掉，把DB interface移入repo
> 
這個東西當初我也猶豫了滿久到底要不要切開
最後決定切開的原因是，原本的 repo 和 bbs.DB 是屬於上下不同層級的東西
現在做出來的 db interface 應該是是屬於和 bbs.DB 的相同層級
所以雖然內容很少，我還是把他切出來了
想問的是 db 那層，之後應該不會要自己實作東西吧?
如果不會的話我覺得可以放回 repo



> 另一個是delivery層的 type httpDelivery struct
> https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/delivery/http/http.go#L11
> 因為我在main.go看到httpDelivery.Run()，覺得httpDelivery不是一般慣用的命名，app.Run()/apiService.Run()/ etc.. 也許比較直觀

delivery 應該是參考最上面那篇文章中兩個連結所命名的
這個同意有點怪怪的不知道是不是命名的關係，改成 httpDelivery.Serve() 會好點嗎
我自己的經驗上做的那層的東西通常都是叫做 server，然後 server.Serve() 這樣
可以看大家覺得哪個英文順眼就改哪個XD

**Comment by mkfsn** [comment]
@Markogoodman 先感謝認領！ ❤️

---

> 這個東西當初我也猶豫了滿久到底要不要切開
最後決定切開的原因是，原本的 repo 和 bbs.DB 是屬於上下不同層級的東西
現在做出來的 db interface 應該是是屬於和 bbs.DB 的相同層級
所以雖然內容很少，我還是把他切出來了
想問的是 db 那層，之後應該不會要自己實作東西吧?
如果不會的話我覺得可以放回 repo

@Markogoodman 我的理解是不需要 db 那層，因為 db 那層的實作應該是會在其他 library ，然後會是去實作 https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L89 所以應該是不用重複定義 interface? 這部分要請 @PichuChen 確認一下我的理解有沒有錯。


---

> 另一個是delivery層的 type httpDelivery struct
https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/delivery/http/http.go#L11
因為我在main.go看到httpDelivery.Run()，覺得httpDelivery不是一般慣用的命名，app.Run()/apiService.Run()/ etc.. 也許比較直觀

> delivery 應該是參考最上面那篇文章中兩個連結所命名的
這個同意有點怪怪的不知道是不是命名的關係，改成 httpDelivery.Serve() 會好點嗎
我自己的經驗上做的那層的東西通常都是叫做 server，然後 server.Serve() 這樣
可以看大家覺得哪個英文順眼就改哪個XD

@Julian-Chu @Markogoodman 這個我覺得是 naming 問題，所以沒什麼太大的意見，以大家最容易了解的去命名就好了～ 😄app.Run 跟 server.Serve 都可以～

不過我想還是可以解釋一下我當初這樣命名的緣由 :D 我之前實作經驗上有做了 gRPC 跟 http (restful) 各自的 delivery ，然後在 main.go 同時 Run ，為了要區分開開來表示，所以就以 xxxDelivery 命名了，當然好不好就是另一回事 XD 

如果是 app.Run/server.Serve 的話，我想要特別注意的應該是，要特別解釋這個 app/server 的範圍涵蓋了什麼吧（像是目前只有 http，或者我們叫它 rest ？我實在是不曉得該怎麼稱呼這個比較恰當 ~語彙能力不足~ ）

**Comment by ars0915** [comment]
想問一下，看到 #23 在驗證 token `CheckPermission` 的部份是放在 usecase 裡，之後有沒有要抽到middleware 的打算呢?

**Comment by KScaesar** [comment]
@Julian-Chu @Markogoodman @PichuChen

>DB interface需要獨立出來一個pkg嗎， 看起來比較偏向是repo內部需要的interface，目前只有mock跟repo會需要它，但是mock DB也是為了repo，可以考慮移進去repo

這個 db 的定義 我覺得有兩個問題
1. 這個介面 應該屬於 go-bbs, 而不是 Ptt-backend
    go-bbs 我覺得比較像是 整潔架構中的 entity 和 Infra 層
    Ptt-backend, 我還是覺得, 比較像 usecase 和 driving 層
    repo 資料夾我怎麼看, 都覺得他像是 Infra 層, 用來實現 entity 層的 相關介面
    可能移到 go-bbs 會比較好?
2. 定義的 method 太過龐大
    BoardRecord, UserRecord, ArticleFile ... 由一個 介面承擔全部, 太重了
    應該先確定, 要把那些元件 組合在一起(我指的是 ddd 的聚合, ddd 中的 repo 是跟隨聚合的)
    然後才定義相關 repo 介面

>@Markogoodman 我的理解是不需要 db 那層，因為 db 那層的實作應該是會在其他 library ，然後會是去實作 https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L89 所以應該是不用重複定義 interface? 這部分要請 @PichuChen 確認一下我的理解有沒有錯。

認同 @mkfsn 所說, 但Connector界面應該拆小, 方向可能是 UserConnector, BoardConnector....

**Comment by KScaesar** [comment]
>delivery 應該是參考最上面那篇文章中兩個連結所命名的
這個同意有點怪怪的不知道是不是命名的關係，改成 httpDelivery.Serve() 會好點嗎
我自己的經驗上做的那層的東西通常都是叫做 server，然後 server.Serve() 這樣
可以看大家覺得哪個英文順眼就改哪個XD

個人覺得 是因為 httpDelivery 被分配了
過多且錯誤職責(不符合命名的職責), 所以才看起來奇怪
[https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/delivery/http/http.go#L24](https://github.com/Markogoodman/Ptt-backend/blob/feat/clean-architecture/internal/delivery/http/http.go#L24)

httpDelivery 我覺得應該只是單純的 httpHandler 
不應該有 run(ListenAndServe) 及 buildRoute 這兩個方法
這兩個行為
應該是在 第三者(客戶端) main 或 依賴注入的函數
而不是在 驅動層(delivery 層)

**Comment by Markogoodman** [comment]
@mkfsn @Min-Feng 

原本使用的 *bbs.DB 是 https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L84 這個 struct 
這 struct 的 method 再去用裡面的 connector 組成自己的 method
ptt-backend 用到的都是這個 DB struct 的 method，並沒有直接去使用 Connector 上的東西
所以應該還是需要自己寫一個 interface

**Comment by Markogoodman** [comment]
> @Julian-Chu @Markogoodman @PichuChen
> 
> > DB interface需要獨立出來一個pkg嗎， 看起來比較偏向是repo內部需要的interface，目前只有mock跟repo會需要它，但是mock DB也是為了repo，可以考慮移進去repo
> 
> 這個 db 的定義 我覺得有兩個問題
> 
> 1. 這個介面 應該屬於 go-bbs, 而不是 Ptt-backend
>    go-bbs 我覺得比較像是 整潔架構中的 entity 和 Infra 層
>    Ptt-backend, 我還是覺得, 比較像 usecase 和 driving 層
>    repo 資料夾我怎麼看, 都覺得他像是 Infra 層, 用來實現 entity 層的 相關介面
>    可能移到 go-bbs 會比較好?
> 2. 定義的 method 太過龐大
>    BoardRecord, UserRecord, ArticleFile ... 由一個 介面承擔全部, 太重了
>    應該先確定, 要把那些元件 組合在一起(我指的是 ddd 的聚合, ddd 中的 repo 是跟隨聚合的)
>    然後才定義相關 repo 介面

我整理一下
目前這個架構是依照這文章發展出來的 https://medium.com/hackernoon/golang-clean-archithecture-efd6d7c43047
所以我都以這篇文章為標準，來看我們做的事情對不對
分別是 Models、Repository、Usecase、Delivery
Models 是用來定義資料的 struct 和他的method，我們這邊是依賴 go-bbs 裡面的資料所以不討論
Usecase 目前做的事情就是邏輯，大家好像比較沒意見也先不討論
Delivery 上面還有一些疑問可能大家要再想想怎麼改

Repository 上面討論的疑問
主要是 db 這個 interface 該放在哪（repo、db、go-bbs），還有到底該不該有這個 interface?

文章內對 Repository 的描述如下
1. 功能方面，依照文章內的敘述 這層是儲存資料庫的 handler (*bbs.DB ) ，會直接用 handler 去取資料，不應該有任何邏輯，只有直接呼叫資料庫的 func
2. 測試方面，請參考文章內 Testing Each Layer：最好是做 integration test（直接讀寫ＤＢ），但也可以使用一些 mock 的 library 例如github.com/DATA-DOG/go-sqlmock

第 1 點 我們的 repository 內目前應該還是會有一點點邏輯存在，例如 https://github.com/Ptt-official-app/Ptt-backend/pull/24 或是 loadUserRecords 以及 (repo *repository) GetUsers 都不是單純的ＤＢ讀寫而已，這部分看要移動到 go-bbs 內或是留著我覺得都可以
第２點 目前我們應該還無法讀寫真正的 db 來做 repo 層的測試 ，因為目前 bbs.DB 大都只有 read 的動作，除非預先就把資料用別的方法放在裡面

這邊想問一下大家覺得要不要留 mock db 和 db interface 這兩個東西？
用的好處是：現在 bbs.DB 只能讀，我們也可以寫 repo 層那些小邏輯的測試  ->  這樣的話 repo 裡面就會放 db interface
用的壞處是：之後要 *bbs.DB operation 多了之後我們其實直接做 integration test 就好了，不然要自己繼續把 mock 的 db 做完而且讀寫要互相配合會很麻煩，等於自己要做一個小資料庫出來  ->  這樣 repo 裡面就是直接放 *bbs.DB ，然後現在就先不寫 repo 這部分的測試ＸＤＤ  自己用真正的檔案手動測一下

雖然這個interface是我自己加的 不過個人傾向先不留ＸＤ 整理了一下感覺缺點比較麻煩

**Comment by mkfsn** [comment]
@Markogoodman 快速回一下，先不論要不要留著 db interface ，我贊成用到 db 的測試都用 integration test XD 然後現在好像已經有 docker image 可以用？

**Comment by KScaesar** [comment]
> @Markogoodman 快速回一下，先不論要不要留著 db interface ，我贊成用到 db 的測試都用 integration test XD 然後現在好像已經有 docker image 可以用？

db 的測試都用 integration test 
但 bbs 的 整合測試, 應該就是要讀取底層檔案階層格式吧
要把這些檔案 放進容器進行整合測試？

以前只有 for 資料庫進行整合測試
不確定 對於 bbs 格式 如何進行整合測試

用 docker 進行整合測試
我查到的有
[https://pkg.go.dev/github.com/ory/dockertest/v3](https://pkg.go.dev/github.com/ory/dockertest/v3)
[https://github.com/orlangure/gnomock](https://github.com/orlangure/gnomock)

**Comment by PichuChen** [comment]
> @mkfsn @Min-Feng
> 
> 原本使用的 *bbs.DB 是 https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L84 這個 struct
> 這 struct 的 method 再去用裡面的 connector 組成自己的 method
> ptt-backend 用到的都是這個 DB struct 的 method，並沒有直接去使用 Connector 上的東西
> 所以應該還是需要自己寫一個 interface

其實目前這個 ISSUE 應該只有涉及程式碼位置的搬動而已，暫時不涉及 interface 的增減，如果要做 interface 的增減應該要另外開 ISSUE。

**Comment by Markogoodman** [comment]
> > @mkfsn @Min-Feng
> > 原本使用的 *bbs.DB 是 https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L84 這個 struct
> > 這 struct 的 method 再去用裡面的 connector 組成自己的 method
> > ptt-backend 用到的都是這個 DB struct 的 method，並沒有直接去使用 Connector 上的東西
> > 所以應該還是需要自己寫一個 interface
> 
> 其實目前這個 ISSUE 應該只有涉及程式碼位置的搬動而已，暫時不涉及 interface 的增減，如果要做 interface 的增減應該要另外開 ISSUE。

沒錯冏

我先來把db那邊拿掉

這樣的話 delivery 那邊是不是也該在開一個新 issue 來決定要怎麼 refactor阿

還有上面的 integration test 部份

不然這串可能討論不完

**Comment by Markogoodman** [comment]
補了一些註解，但很多func我其實不知道實際功能所以只是敘述而已，或許之後有人可幫補

目前該改的地方應該差不多了 看大家還有沒有意見～

**Comment by mkfsn** [comment]
非常感謝大家的參與跟意見！ #23 被 merge 了之後，我想我們可以先 close 這個 issue。

如果有任何問題我們就開另一張 issue 討論吧～
