### ISSUE TITLE
[主線] [PTT] 實作個人看板歷史留言 usecase

### ISSUE THREAD

**Issue by SivWatt** [Ptt-official-app/Ptt-backend#161]
### 實作細節 / Details of Implement
- 此為 #60 子ISSUE
- usecase 部分應該是直接將 repository 的結果輸出即可。
- 修改 [usecase.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/usecase.go)
    - 新增介面函式: `GetUserComments(ctx context.Context, userID string)`
- 修改 [usecase/user.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/user.go)
    - 新增函式: `func (usecase *usecase) GetUserComments(ctx context.Context, userID string)`
- 修改 [usecase/user_test.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/user_test.go)
    - 新增測試函式
- 修改 [usecase/user_mock_test.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/user_mock_test.go)
    - 新增mock函式

### 期程 / Schedule
- 討論時間： 一週, 到 4/7
- 實作時間：一週, 到 4/14
- 確認時間：一週, 到 4/21

### 相關文件 / Documents
#60 
[PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by SivWatt** [comment]
確認一下～這邊應該是接repository的return然後往回丟嘛

**Comment by PichuChen** [comment]
對

**Comment by SivWatt** [comment]
所以組json就是在repository那邊組
那這邊應該可以接起來寫個mock就搞定

**Comment by SivWatt** [comment]
那我就找時間把這個做掉～
