### ISSUE TITLE
[主線] [PTT] 實作個人看板歷史留言 repository

### ISSUE THREAD

**Issue by SivWatt** [Ptt-official-app/Ptt-backend#162]
### 實作細節 / Details of Implement
- 此為 #60 子ISSUE
- repository 部分歷史留言功能應該由 go-bbs 儲存還是 Ptt-backend 掃描後暫存需要討論，暫定由 go-bbs 儲存。
- 修改 [repository.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/repository.go)
  - 新增介面函式: `GetUserComments(ctx context.Context, userID string)`
- 修改 [repository/user.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/user.go)
  - 新增函式: `func (repo *repository) GetUserComments(_ context.Context, userID string)`
- 修改 [repository/user_test.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/user_test.go)
  - 新增函式: `func TestGetUserComments(t *testing.T)`

### 期程 / Schedule
- 討論時間： 一週, 到 4/7
- 實作時間：一週, 到 4/14
- 確認時間：一週, 到 4/21

### 相關文件 / Documents
#60 
[PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by SivWatt** [comment]
這個我來做

**Comment by SivWatt** [comment]
想確認一下這邊應該我的理解會是由`go-bbs`定義好資料結構以及method 
然後`repository`這邊使用method傳入 userID 拿回結果
所以要馬這邊先抽象化作掉 不然就是`go-bbs`做好 這邊直接接起來嗎

**Comment by PichuChen** [comment]
> 想確認一下這邊應該我的理解會是由`go-bbs`定義好資料結構以及method
> 然後`repository`這邊使用method傳入 userID 拿回結果
> 所以要馬這邊先抽象化作掉 不然就是`go-bbs`做好 這邊直接接起來嗎

如果說 go-bbs 已經有定義好的資料結構和 method 的話就是採用 go-bbs 的，不然就是在 pb 這邊定義一個然後再看後面檢討這樣。

然後我印象中 go-bbs 已經有對應個人看板歷史留言的 method 了。

https://github.com/Ptt-official-app/go-bbs/pull/75/files

在這邊，如果覺得OK也可以幫我回個 LGTM 那這樣我就把他merge進去這樣

**Comment by SivWatt** [comment]
> 
> 
> > 想確認一下這邊應該我的理解會是由`go-bbs`定義好資料結構以及method
> > 然後`repository`這邊使用method傳入 userID 拿回結果
> > 所以要馬這邊先抽象化作掉 不然就是`go-bbs`做好 這邊直接接起來嗎
> 
> 如果說 go-bbs 已經有定義好的資料結構和 method 的話就是採用 go-bbs 的，不然就是在 pb 這邊定義一個然後再看後面檢討這樣。
> 
> 然後我印象中 go-bbs 已經有對應個人看板歷史留言的 method 了。
> 
> https://github.com/Ptt-official-app/go-bbs/pull/75/files
> 
> 在這邊，如果覺得OK也可以幫我回個 LGTM 那這樣我就把他merge進去這樣

他這個好像是使用者歷史文章
裡面沒有跟comment 有關的record

**Comment by PichuChen** [comment]
那...看起來是還沒實作...

**Comment by SivWatt** [comment]
那我還是先回[]interface{}好了
註解一下之後要改掉

**Comment by SivWatt** [comment]
這個ISSUE #161 已經做了一部分 除了 test code _(感覺在db 可以mock之前好像都沒意義 是可以驗hard code 結果 XDD)_
目前是直接回一個 hard code 結果 因為 go-bbs 看起來是還沒有實作
這邊沒有concern是不是可就可以close了
