### ISSUE TITLE
[主線] [PTT] 實作熱門看板的看板列表 usecase/board

### ISSUE THREAD

**Issue by AmberFu** [Ptt-official-app/Ptt-backend#164]
### 實作細節 / Details of Implement

- 此為 #51 子ISSUE
- 修改 [board.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/board.go)
  - 實作函式 `GetPopularBoards()`
- 注意 - 兩個可行方向：
  - 「利用 GetBoards 後再一個一個篩選」
  - 「從 Ptt-backend 發起有邏輯性的篩選條件（例如where is_hidden = 0）」帶入主流 DBMS 的概念

### 期程 / Schedule

- 討論時間： 一週, 到 4/7
- 實作時間： 一週, 到 4/14
- 確認時間： 一週, 到 4/21

### 相關文件 / Documents
- 主issue： #51
- [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit)

**Comment by whitefloor** [comment]
hi~~~請assign這個給我

**Comment by whitefloor** [comment]
補充router當紀錄怕下次忘記
/v1/popular-boards

**Comment by whitefloor** [comment]
我想請問判斷的條件是要等go-bbs新增嗎？
目前照討論的方向使用GetBoards只能取得BoardID/Title/IsClass/ClassID/BM
除了ClassID之外好像都沒辦法當作篩選條件

**Comment by PichuChen** [comment]
> 我想請問判斷的條件是要等go-bbs新增嗎？
> 目前照討論的方向使用GetBoards只能取得BoardID/Title/IsClass/ClassID/BM
> 除了ClassID之外好像都沒辦法當作篩選條件

什麼篩選條件？

**Comment by whitefloor** [comment]
篩選熱門看板的條件

我想說可能有某些被隱藏 或是不能留言的看板 會有ID或是一些status可以先過濾掉
最後在用user進入看板的次數去篩選熱門看板

不知道現在有沒有這些field

**Comment by PichuChen** [comment]
目前在 API 上面沒有，不過你可以把這些東西用 TODO 註解的方式先放上

然後被隱藏的看板可能要實作一個 `shouldBeDisplayOnPouplarList` 之類的 method,
其中規則的部分可能也是要先放註解打 TODO, 因為要去調一下原本 pttbbs 是如何判斷的

**Comment by whitefloor** [comment]
好的 這樣我理解了
今天我會做完這個跟repo的部分，非常感謝
