### ISSUE TITLE
[主線] [PTT] 實作個人看板的使用者資訊usecase

### ISSUE THREAD

**Issue by fish-dumpling** [Ptt-official-app/Ptt-backend#165]
### 實作細節 / Details of Implement
- #52 子issue
- usecase 部分應該是直接將 repository 的結果輸出即可。
- 修改 [usecase/user_test.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/user_test.go)
新增測試函式 TestGetUserInformation
- TODO: Check Etag or Not-Modified for cache (?)
註解上看到這條，我們目前有在其他地方實作過cache嗎？或者這邊不需要？

### 期程 / Schedule
- 討論時間： 3天
- 實作時間： 1天
- 確認時間： 1天

### 相關文件 / Documents
- [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)
- #52

**Comment by PichuChen** [comment]
Cache 的部分幫忙留著註解

**Comment by PichuChen** [comment]
> ### 實作細節 / Details of Implement
> * #52 子issue
> * usecase 部分應該是直接將 repository 的結果輸出即可。
> * 修改 [usecase/user_test.go](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/usecase/user_test.go)
>   新增測試函式 TestGetUserInformation
> * TODO: Check Etag or Not-Modified for cache (?)
>   註解上看到這條，我們目前有在其他地方實作過cache嗎？或者這邊不需要？
> 
> ### 期程 / Schedule
> * 討論時間： 3天
> * 實作時間： 1天
> * 確認時間： 1天
> 
> ### 相關文件 / Documents
> * [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)
> * #52

目前還沒統一實作，接下來會需要做，不過Cache 應該是做在Delivery層那邊？

**Comment by SivWatt** [comment]
這個我做～

**Comment by SivWatt** [comment]
想請問一下這個issue
目前`usecase`裡面已經實作了 `GetUserInformation()` 實作的內容看起來也OK 
請問這個 issue 實際希望要做到的是什麼 
test case 的話按照我的理解應該是驗證 MockUser return 的那些值
_另外關於 `fmt.Sprintf()` 的部分 我記得使用 `strconv.FormatInt()` 或是 `strconv.Itoa()` 效率更好_

**Comment by PichuChen** [comment]
這個要串接 #100   和 #58 的相關成果，參考 Mock 的 GetUserInformation 去實作真正的 GetUserInformation ，印象中目前的實作應該還是Mock 實作？

> 另外關於 fmt.Sprintf() 的部分 我記得使用 strconv.FormatInt() 或是 strconv.Itoa() 效率更好

這部分看有沒有實際資料

**Comment by SivWatt** [comment]
> > 另外關於 fmt.Sprintf() 的部分 我記得使用 strconv.FormatInt() 或是 strconv.Itoa() 效率更好
> 
> 這部分看有沒有實際資料

我自己做了一個 benchmark test 跑出了兩個結果，可以參考一下。
可以直接看 `Run benchstat with benchmark result` 這一個步驟
[golang_1.14](https://github.com/SivWatt/go-string-convert-benchmark/runs/2400853766?check_suite_focus=true)
[golang_1.16](https://github.com/SivWatt/go-string-convert-benchmark/runs/2400853795?check_suite_focus=true)

**Comment by PichuChen** [comment]
相較起來差了快三倍
