### ISSUE TITLE
[主線] [PTT] 實作儲存草稿 - delivery/http

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#166]
### 實作細節 / Details of Implement
- 此為 #61 的子任務
- 修改 route.go 與 route_user.go 並在 route_user_test.go 補上測試
### 期程 / Schedule
- 討論時間：一週, 到 4/14
- 實作時間： 一週, 到 4/21
- 確認時間： 一週, 到 7/28

### 相關文件 / Documents
[API文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.p7g3lzj85fw8)

**Comment by nickyanggg** [comment]
我可以幫忙這個～

**Comment by nickyanggg** [comment]
請問是一次實作取得、儲存、刪除草稿三種 method 嗎？還是只要先實作取得的部分就好？

**Comment by PichuChen** [comment]
可以做一個PR一個

**Comment by nickyanggg** [comment]
這個還有儲存草稿 (POST) 以及刪除草稿 (DELETE) 未實作，目前正在實作 POST 的部分，還是剩下二個要另外重開 issue？
