### ISSUE TITLE
[主線] [PTT] 實作儲存草稿 - repository

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#167]
### 實作細節 / Details of Implement
- 此為 #61 的子任務
- 修改 repository.go 與 user.go
- 因 go-bbs 尚未實作相關功能，可先 mock 一個結構出來儲存草稿，之後實作刪除草稿與取得草稿時可重用這個結構
- 要回傳 error
### 期程 / Schedule
- 討論時間：一週, 到 4/14
- 實作時間： 一週, 到 4/21
- 確認時間： 一週, 到 7/28

### 相關文件 / Documents
[API文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.p7g3lzj85fw8)

**Comment by weizhe0422** [comment]
我可以幫忙這個

**Comment by PichuChen** [comment]
> 我可以幫忙這個

OK, 如果有問題的話再到 Slack 或是這邊發問

**Comment by PichuChen** [comment]
@weizhe0422  想確認一下目前這個 ISSUE 進度到哪邊了？

**Comment by titaneric** [comment]
我可以幫忙這個，請給我一個禮拜完成

**Comment by PichuChen** [comment]
> 我可以幫忙這個，請給我一個禮拜完成

麻煩你了
