### ISSUE TITLE
[主線] [PTT] 實作儲存草稿 - usecase

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#168]
### 實作細節 / Details of Implement
- 此為 #61 的子任務
- 修改 usecase.go 與 user.go 並在 user_test.go 補上測試
- 應該直接呼叫 repository 提供的 function 即可
- 要回傳 error
### 期程 / Schedule
- 討論時間：一週, 到 4/14
- 實作時間： 一週, 到 4/21
- 確認時間： 一週, 到 7/28

### 相關文件 / Documents
[API文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.p7g3lzj85fw8)

**Comment by nickyanggg** [comment]
我可以幫忙這個~
