### ISSUE TITLE
[主線] [PTT] 增加 route_token 註解

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#173]
### 實作細節 / Details of Implement
主要是增加 route_token 相關註解
可參考 #110 

### 期程 / Schedule
- 討論時間： 三天
- 實作時間：三天
- 確認時間： 一天

### 相關文件 / Documents
route_token.go , route_token_test.go , route_token_mock_test.go

**Comment by techeternalriverco** [comment]
我可以幫忙這個，麻煩 assign 給我，但我需要 3 天的實作時間。謝謝。
