### ISSUE TITLE
[主線] [PTT] 增加 route_borad 相關註解

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#175]
### 實作細節 / Details of Implement
主要是增加 route_borad 相關註解
可參考 #110 

### 期程 / Schedule
- 討論時間： 三天
- 實作時間：一天
- 確認時間： 一天

### 相關文件 / Documents
 route_boards.go, route_boards_test.go , route_boards_mock_test.go

**Comment by unknowntpo** [comment]
請 assign 給我，謝謝。

**Comment by y2468101216** [comment]
ok
