### ISSUE TITLE
[主線] [PTT] 增加 route_boards_articles 相關註解

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#176]
### 實作細節 / Details of Implement
主要是增加 route_boards_articles 相關註解
可參考 #110 

### 期程 / Schedule
- 討論時間： 三天
- 實作時間：一天
- 確認時間： 一天

### 相關文件 / Documents
route_boards_articles.go , route_boards_articles_test.go

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？

**Comment by y2468101216** [comment]
先關了它，短時間內也沒時間處理這件事
