### ISSUE TITLE
[主線] [PTT] 實作 發文 http 

### ISSUE THREAD

**Issue by DeanXu2357** [Ptt-official-app/Ptt-backend#177]
### 實作細節 / Details of Implement
- 添加 route
- route_board_articles.go 新增對應的 function
- 新增簡單的 response testcase ，確認 route 打的通
- 更新 swagger.yml

### 期程 / Schedule
- 討論時間： 一週
- 實作時間： 一週
- 確認時間： 一週

### 相關文件 / Documents
主 Issue #25 
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)
[Swagger](https://pttapp.cc/swagger/)

**Comment by DeanXu2357** [comment]
@PichuChen 這個讓我來幫忙吧

**Comment by PichuChen** [comment]
> @PichuChen 這個讓我來幫忙吧 

麻煩你了
