### ISSUE TITLE
[建議] 把在 go-bbs 的 ISSUE_TEMPLATE 複製一份過來

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#18]
**原本作法的問題 / Solved Problem**
- 原本就沒有 ISSUE TEMPLATE 很不方便。

**實作細節 / Details of Implement**
- 從  https://github.com/Ptt-official-app/go-bbs/tree/development/.github/ISSUE_TEMPLATE 把東西複製過來這個專案
- 如果可以把名稱改好看一點應該會更好

**期程 / Schedule**
N/A

**相關文件 / Documents**
https://github.com/Ptt-official-app/go-bbs/tree/development/.github/ISSUE_TEMPLATE

**Comment by lavaday1225** [comment]
在主目錄新增 .github/ISSUE_TEMPLATE ，適當修改參考的template內容後複製過來

有需要 PULL_REQUEST_TEMPLATE 嗎？

**Comment by PichuChen** [comment]
修改部分如果覺得不需要討論的修改可以直接改，覺得需要討論的修改可以在 ISSUE 這邊回應討論之後取得共識在進行。
另外如果這個修改也適合放在 go-bbs 的話那也可以在那邊開 ISSUE 修改。

然後 PULL_REQUEST_TEMPLATE 這個也要，感謝。
