### ISSUE TITLE
[主線] [PTT] 實作發文 repository

### ISSUE THREAD

**Issue by DeanXu2357** [Ptt-official-app/Ptt-backend#180]
### 實作細節 / Details of Implement
- repository 中新增發文的 function 與對應的 interface

### 期程 / Schedule
- 討論時間： 五天
- 實作時間： 五天
- 確認時間： 五天

### 相關文件 / Documents
主 Issue #25 
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)
[Swagger](https://pttapp.cc/swagger/)

**Comment by DeanXu2357** [comment]
我想幫忙

**Comment by DeanXu2357** [comment]
@PichuChen 
看了一下，我可不可以改先做這個
https://github.com/Ptt-official-app/go-bbs/issues/79
有一些結構還沒出來，repo 有點難寫，實做完這個再回頭應該會比較簡單吧

**Comment by DeanXu2357** [comment]
整理一下
就目前來看
bbs.ArticleRecord 需要新增回傳 text(文章內容)
UserRecord 需要新增 sender_site, ip , country , signature (簽名檔？)

另外 api response 內容中的 board_name , 雖然可以用 board_id 在查找一次 go_bbs 。
如果可以在和 go-bbs 新增資料時，就回傳回來就可以少一次 request 了。

**Comment by PichuChen** [comment]
我印象中好像有問其他人幫忙做了，可能要確認分配表，不過理論上是可以先用mock 的方式假設底層會回傳什麼來做開發。
