### ISSUE TITLE
[主線] [PTT] 實作熱門看板的看板列表 repository

### ISSUE THREAD

**Issue by whitefloor** [Ptt-official-app/Ptt-backend#181]
### 實作細節 / Details of Implement

- repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。

### 期程 / Schedule

- 討論時間： 3天, 4/15-4/17
- 實作時間： 3天, 4/18-4/20
- 確認時間： 3天, 4/21-4/23

### 相關文件 / Documents

- 主Issue: #51
- [PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit)
- /v1/popular-boards

**Comment by whitefloor** [comment]
我想請問熱門看板有另外儲存嗎？
還是是使用GetBoards撈看板出來再到usecase判斷？

**Comment by PichuChen** [comment]
@whitefloor  想確定一下目前這個 ISSUE 狀態到哪邊了？

**Comment by whitefloor** [comment]
照 #51 的討論這個應該不用實作
目前是使用 usecase.repo.GetBoards(ctx) 將看板全部撈出來
在usecase進行篩選
