### ISSUE TITLE
[一般] 貢獻者名單

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#182]
### 實作細節 / Details of Implement
因為第一期 milestone 即將結束，目前準備製作一份貢獻者名單加到專案裡面。
包括但不限於 coding，撰寫文件等

歡迎大家提名自己到名單內

### 期程 / Schedule
無，但會定時 merge 到 development

### 相關文件 / Documents
CONTRIBUTORS.md

提名格式如下:

1. 名字 （網路名稱）：必填
2. GitHub 帳號：非必填
3. 社交帳號：非必填，請給連結
4. 貢獻內容：必填

**Comment by y2468101216** [comment]
1. 名字 （網路名稱）：陳昱廷
2. GitHub 帳號：[y2468101216](https://github.com/y2468101216)
3. 社交帳號：[facebook](https://www.facebook.com/y2468101216)
4. 貢獻內容：coding

**Comment by SivWatt** [comment]
1. 名字 （網路名稱）：SivWatt、涼涼
2. GitHub 帳號：[SivWatt](https://github.com/SivWatt)
3. 社交帳號：
4. 貢獻內容：coding

**Comment by whitefloor** [comment]
1. 名字 （網路名稱）：whitefloor
2. GitHub 帳號：[whitefloor](https://github.com/whitefloor)
3. 社交帳號：x
4. 貢獻內容：coding/code review

**Comment by nickyanggg** [comment]
1. 名字 （網路名稱）：nickyanggg
2. GitHub 帳號：[nickyanggg](https://github.com/nickyanggg)
3. 社交帳號：[facebook](https://www.facebook.com/yang.z.lin.90)
4. 貢獻內容：coding

**Comment by gogog22510** [comment]
名字 （網路名稱）：gogog22510
GitHub 帳號：gogog22510
社交帳號：x
貢獻內容：coding
