### ISSUE TITLE
[主線] [PTT] 實作Mail Provider

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#191]
### 實作細節 / Details of Implement
- [x] 實作 smtp (以 mailgun 的smtp server 為範例) #196 
- [x] 實作 mailgun api #197
- 實作其他 Provider

目前想法是這樣，會用 connection string 的方式來做連線初始化
例如 `smtp://mailgun.org:444?username=123&apk_key=456`  `mailgun://mailfun:333?api_key=444`  這樣

目前介面請參考 https://github.com/Ptt-official-app/Ptt-backend/tree/development/internal/mail

### 期程 / Schedule
- 討論時間： 一週，4/30
- 實作時間： 一週，5/7
- 確認時間： 一週，5/14

**Comment by y2468101216** [comment]
拆成兩個子項吧，一個是 smtp 一個是 mailgun

**Comment by y2468101216** [comment]
assign 給我吧
