### ISSUE TITLE
[主線] [PTT] 實作文章推文 repository

### ISSUE THREAD

**Issue by gogog22510** [Ptt-official-app/Ptt-backend#194]
### 實作細節 / Details of Implement
此為 #68 子任務
主要實作 repository 的部分，BBS library部分未完成的話可以mock ，並完成 testcase。
實作完成後推至 development

### 期程 / Schedule
- 討論時間：2天，到 04/26
- 實作時間：1周，到 05/02
- 確認時間：2天，到 05/04

### 相關文件 / Documents
主任務 #68
[PTT 後端協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)

**Comment by gogog22510** [comment]
請問跟bbs library聯絡部分也是mock就好嗎?

**Comment by PichuChen** [comment]
那個聯絡部分？

**Comment by gogog22510** [comment]
不好意思，可能前面問題不太明確。想請問bbs那邊相對應的method作好了嗎? 還是我需要回傳假的result?

**Comment by PichuChen** [comment]
> 不好意思，可能前面問題不太明確。想請問bbs那邊相對應的method作好了嗎? 還是我需要回傳假的result?

假如 go-bbs 還沒好的話，就先回傳假的result 即可

**Comment by titaneric** [comment]
我可以試試這個，請給我一周時間完成
