### ISSUE TITLE
[主線] [PTT] 實作Mail Provider - mailgun api

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#197]
### 實作細節 / Details of Implement
- 相關討論於 #191
- 這是實作 mailgun api

### 期程 / Schedule
- 討論時間：一天
- 實作時間：三天
- 確認時間：一天

### 相關文件 / Documents
#191
[mailgun 文件](https://documentation.mailgun.com/en/latest/api-sending.html#sending)

**Comment by PichuChen** [comment]
雖然 mailgun 有 golang SDK ，不過到底是要用 Golang SDK 還是實作curl 就好了可能需要討論。

**Comment by SivWatt** [comment]
我們是不是盡量不要用到外部的package 
如果是的話 是可以用`http`自己照著刻一套出來 XD
reference: [mailgun send](https://github.com/mailgun/mailgun-go/blob/a87d271e01bf098b5bf2a1998ebd910bff873c0d/messages.go#L531)

**Comment by PichuChen** [comment]
@SivWatt 你那邊有要接這個ISSUE嗎？

**Comment by SivWatt** [comment]
好 我來做
1. 所以config會是 mailgun://xxxx 然後我判斷是這個schem就 newMailgunProvider 
2. Send method就實作 Mail interface 用http 組request打到host

不過好像沒有可以測試的domain對吧 這樣要怎麼驗證比較好

**Comment by PichuChen** [comment]
> 好 我來做
> 
> 1. 所以config會是 mailgun://xxxx 然後我判斷是這個schem就 newMailgunProvider
> 2. Send method就實作 Mail interface 用http 組request打到host
> 
> 不過好像沒有可以測試的domain對吧 這樣要怎麼驗證比較好

domain 會用 pttapp.cc 這個你再用Slack和我聯絡

**Comment by PichuChen** [comment]
@SivWatt  想確定一下目前進度到哪邊了？

**Comment by SivWatt** [comment]
上禮拜週末比較沒空 這週會抓空閒的時間處理
