### ISSUE TITLE
有要求只使用原生標準庫？

### ISSUE THREAD

**Issue by Min-Feng** [Ptt-official-app/Ptt-backend#2]
viper: config 讀取
testing: testify

這兩個應該是go很常見的pkg
在這專案也不使用嘛？

用介面隔開就不會和業務邏輯耦合
相關的第三方庫吧？

**Comment by PichuChen** [comment]
從優點來說，第三方元件庫可以不用重新造輪子，同時也會有人可以用其熟悉的工具。

缺點來說，第三方元件庫造成需要檢查的範圍變大，輪子規格如果未來變動時會有是否跟進的問題以及未來是不是作者會停止維護等等之類的問題，另外是對於不熟悉該工具的人來說也會增加學習負擔（相對於官方套件(package)）

對於兩個套件(package)我稍微分享一下當時決定的想法是如何：
config 讀取的部分我先前都是使用 json 作為 config 檔，但是他在維運上面會有不便，因為不容易進行註解。
所以後來我考慮的是 yaml, 但是 yaml 沒有官方套件，因此可能得引入外部套件。
後來變成在 yaml 和 toml 之間選擇，發現 toml 比起 yaml 來說類似以前的 INI 檔格式。
另外 toml 不需要處理縮排，因此未來在透過 vim 修改設定檔的環境應該也會比較方便。

所以就暫定了以 toml 作為設定檔的檔案格式。

接下來是選擇套件， viper 當時有看到他，最後沒有選擇 viper 的原因是我們不會用到那麼多的功能，我們如果只要讀取 TOML (還不含寫入) 的話，目前的套件就符合需求了。

testify 的部分我比較沒有意見，在 [Go-bbs](https://github.com/PichuChen/go-bbs) 中因為他是函式庫所以會比較希望減少第三方套件(package)的引入量，避免其他利用者引入後會同時引入一大堆套件。但這個套件不太會再被其他人引入，所以可能就看看其他人有沒有反對意見這樣。

**Comment by Markogoodman** [comment]
你好~
藉這個標題問一下
在README裡面有看到說不想用 http framework 會增加維護成本，不過有點不太理解是哪種維護成本，是覺得 framework 可能有bug之類的嗎(?

像是gin這種還滿成熟的框架其實滿多公司產品都會用，也很多人在維護
看了一下專案內有很多 API 都要做 authentication 還有像是什麼 IP flowspeed之類的
就可以用這些框架的middleware來做
不然我們就是要自己做一個middleware package出來感覺維護成本和擴充性都比不上gin

**Comment by PichuChen** [comment]
> 你好~
> 藉這個標題問一下
> 在README裡面有看到說不想用 http framework 會增加維護成本，不過有點不太理解是哪種維護成本，是覺得 framework 可能有bug之類的嗎(?
> 
> 像是gin這種還滿成熟的框架其實滿多公司產品都會用，也很多人在維護
> 看了一下專案內有很多 API 都要做 authentication 還有像是什麼 IP flowspeed之類的
> 就可以用這些框架的middleware來做
> 不然我們就是要自己做一個middleware package出來，感覺維護成本和擴充性都比不上gin

我覺得 gin 的問題確實可以另外開一個 ISSUE 出來討論，畢竟如果只是討論是否引入函式庫或是套件的標準的話在這邊就可以了，但是如果是討論特定套件的話應該另外開立另一個 ISSUE 會比較好。

普遍性的原因在上面的回應中有提及，針對 gin 單個套件的原因需要把 gin 整個套件 review 完才比較能給出完整的意見。
