### ISSUE TITLE
[主線] [PTT]  End To End Test millstone1

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#208]
### 實作細節 / Details of Implement
目前有幾個想法實做測試

1. 手動測試 - 最簡單，但難重現
2. postman test - 最難，但不需要用 golang，使用類 js 語言開發
3. golang test - 使用 http/curl 實做，可以整合進 ci

我會先實做一個 golang 的 e2e 測試供大家參考，大家可以下方討論有沒有更好的作法

### 期程 / Schedule
- 討論時間：一週
- 實作時間： 未定
- 確認時間： 未定

### 相關文件 / Documents
[測試表](https://docs.google.com/spreadsheets/d/1uo4AJuSi5xTXEht2o2EHogLivCJlJqlLaeqoj1RceDY/edit#gid=0)

**Comment by PichuChen** [comment]
我覺得最終可以讓他們都變成用 Golang 來做測試，這個沒問題，現在想解決的問題主要是在測試項目有沒有意義以及是否完整的這件事情上。

對於這件事情我認為自然語言可以比程式語言更容易來幫我們確認我們的測試項目在做什麼測試。

那實際上在手動測試跑過之後，也是可以花人力轉換成 testing code ，然後把原有的自然語言改成用英文寫補在該項 testing 的註解區域這樣。

換句話說，如果因為寫 Golang 比較麻煩、還要做 PR 比較麻煩等等的理由讓測試不夠完備的話這樣會比較可惜，因此這階段我認為先用比較容易寫的自然語言來描述需要測試什麼東西，這樣測試項目才會多，然後測試的內容也會比較趨向有意義。

**Comment by y2468101216** [comment]
我是覺得不衝突，從現在的表看起來應該分配下去同時兩個一起做掉不會太難

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？

**Comment by y2468101216** [comment]
先關了它，短時間內也沒時間處理這件事
