### ISSUE TITLE
[BUG] 不放入 Access Token 的時候 GET /v1/users/SYSOP/information 不應該取得任何人的資料

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#216]
### 發生了什麼事？ / The Problem
沒帶 token 的時候不應回傳使用者資料

<img width="1040" alt="截圖 2021-06-08 下午10 22 09" src="https://user-images.githubusercontent.com/600238/121202574-faef1c00-c8a7-11eb-87fd-52248b53812c.png">

### 如何重現 / To Reproduce
不放入 Access Token 的時候 GET /v1/users/SYSOP/information 取得了 SYSOP 的資料

1. 使用預設的測試資料
2. curl 'localhost:8081/v1/users/SYSOP/information' (或是用 postman)
3. 取得 SYSOP 資料 (不應該要取到的）

### 預期的行為 / Expected behavior
不放入 Access Token 的時候 GET /v1/users/SYSOP/information 不應該取得任何人的資料

應該要出現錯誤訊息 
```
{
    "error": "permission_error",
    "error_description": "no permission"
}
```
另外要出現 4 開頭的 HTTP Status

### 螢幕截圖 / Screenshots
![螢幕擷取畫面 2021-06-08 112204](https://user-images.githubusercontent.com/10670845/121118203-090f4f00-c84c-11eb-8c50-7fd39552e4bc.jpg)

https://docs.google.com/spreadsheets/d/1dyfmWZJaTiDrSMIFZ6ynmfeTWU3h45ScW1eyKFJU494/edit?usp=sharing

### 開發環境 / Environment
windows 10
golang 1.16

**Comment by ichiaohsu** [comment]
請問一下關於這個 issue，是不是已經被 #224 解掉了？看起來已經拿到正確的 401 status code，只差 response 不正確

**Comment by y2468101216** [comment]
應該是

**Comment by ichiaohsu** [comment]
我可以把 error response 修一下嗎？

**Comment by y2468101216** [comment]
歡迎提交 pr ， 可以的話順便檢查其他的是否回傳也有問題
