### ISSUE TITLE
[BUG] 不放入 Access Token 的情況下 GET /v1/users/SYSOP/articles 不應該看到任何文章，應該要看到 error 元素

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#220]
### 發生了什麼事？ / The Problem
不放入 Access Token 的情況下 GET /v1/users/SYSOP/articles 看到了 item = null
![螢幕擷取畫面 2021-06-09 134825](https://user-images.githubusercontent.com/10670845/121300425-65946c00-c929-11eb-88cd-7a2c77e76fab.jpg)

### 如何重現 / To Reproduce
不放入 Access Token 的情況下 GET /v1/users/SYSOP/articles 看到了 item = null
1. 使用預設的測試資料
2. curl 'localhost:8081/v1/users/SYSOP/articles' (或是用 postman)
3. 取得 SYSOP 資料 (不應該要取到的）

### 預期的行為 / Expected behavior
不放入 Access Token 的情況下 GET /v1/users/SYSOP/articles 不應該看到任何文章，應該要看到 error 元素

應該要出現錯誤訊息 
```
{
    "error": "permission_error",
    "error_description": "no permission"
}
```
另外要出現 403 的 HTTP Status

### 螢幕截圖 / Screenshots
![螢幕擷取畫面 2021-06-08 115518](https://user-images.githubusercontent.com/10670845/121120594-73c28980-c850-11eb-87e9-e70484dcefc2.jpg)

### 開發環境 / Environment
windows 10
golang1.16

**Comment by PichuChen** [comment]
在 [testcase 2021060401](https://docs.google.com/spreadsheets/d/1RGIQPN6KfiCzWRQe-BeTXFUTvdwytOv0Yhd5a8ixCLk/edit?usp=sharing) 中的 C5-1-1 測試項目中發現有問題

**Comment by y2468101216** [comment]
![螢幕擷取畫面 2021-06-30 152449](https://user-images.githubusercontent.com/10670845/123920274-5c427080-d9b8-11eb-86f0-898a70a8676e.jpg)

**Comment by y2468101216** [comment]
![螢幕擷取畫面 2021-06-30 153243](https://user-images.githubusercontent.com/10670845/123920342-6d8b7d00-d9b8-11eb-9d9c-713efbadb92c.jpg)

**Comment by PichuChen** [comment]
C5-1-1 是 boards 不是 users, 我這邊搞錯了，所以關掉這個
