### ISSUE TITLE
[BUG] 放入 Access Token 之後， GET /v1/users/SYSOP/comments 應該看到 SYSOP 曾經發過的推文

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#222]
### 發生了什麼事？ / The Problem
放入 Access Token 之後， GET /v1/users/SYSOP/comments 看到 no value
![螢幕擷取畫面 2021-06-09 140116](https://user-images.githubusercontent.com/10670845/121301737-3979ea80-c92b-11eb-9f5c-aaa50bdb85cc.jpg)

### 如何重現 / To Reproduce
放入 Access Token 之後， GET /v1/users/SYSOP/comments 看到 no value

1. 使用預設的測試資料
2.curl --location --request GET 'http://localhost:8081/v1/users/SYSOP/comments'
--header 'Authorization: Bearer {token}'
(或是用 postman)
3. 取得 SYSOP 資料，但資料都是 no value

### 預期的行為 / Expected behavior
放入 Access Token 之後， GET /v1/users/SYSOP/comments 應該看到 SYSOP 曾經發過的推文

### 螢幕截圖 / Screenshots
![螢幕擷取畫面 2021-06-08 120059](https://user-images.githubusercontent.com/10670845/121121298-e718cb00-c851-11eb-9b91-6449199ba2ce.jpg)

### 開發環境 / Environment
windows 10
golang 1.16

**Comment by y2468101216** [comment]
這個 bug 是因為 go-bbs

**Comment by PichuChen** [comment]
在 [testcase 2021060401](https://docs.google.com/spreadsheets/d/1RGIQPN6KfiCzWRQe-BeTXFUTvdwytOv0Yhd5a8ixCLk/edit?usp=sharing) 測試到這個問題 編號 C2-6-2

**Comment by y2468101216** [comment]
經討論過後發現是 /v1/boards/SYSOP/articles 故關閉
