### ISSUE TITLE
[主線] [PTT] 實作顯示看板發文限制以及細部資訊  (串接 go-bbs)

### ISSUE THREAD

**Issue by nickyanggg** [Ptt-official-app/Ptt-backend#225]
### 實作細節 / Details of Implement

- 因為當初 go-bbs 尚未實作上述功能，因此 Ptt-backend 實作都是先用 mock 來處理。
- 移除 mock 的部分並串接 go-bbs 所提供的 interface。
### 期程 / Schedule

- 討論時間：一週
- 實作時間：一週
- 確認時間：一週

### 相關文件 / Documents

[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1g6ovfezg1)

**Comment by PichuChen** [comment]
是打算在 Usecase 補上嗎？

**Comment by nickyanggg** [comment]
> 是打算在 Usecase 補上嗎？

發文限制是在 usecase 補上，細部資訊則是寫在 http/route_boards.go 中的 marshalBoardSettings

**Comment by PichuChen** [comment]
> > 是打算在 Usecase 補上嗎？
> 
> 發文限制是在 usecase 補上，細部資訊則是寫在 http/route_boards.go 中的 marshalBoardSettings

我一開始看錯標題，本來以為是發文是檢查限制的意思

**Comment by nickyanggg** [comment]
了解，可能我標題寫得不太清楚 xd
