### ISSUE TITLE
[主線] [PTT] 實作上下箭頭推文 - repository

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#232]
### 實作細節 / Details of Implement

- 參照主 issue #210 說明 
- 在repository/article.go中新增Usefulness struct，與後端gobbs對接
- 對應測試需要撰寫
### 期程 / Schedule
- 討論時間： 二天, 到 6/23
- 實作時間： 一天, 到 6/24
- 確認時間： 二天, 到 6/26

### 相關文件 / Documents
[API文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.r3t24bsqupvy)

補充目前 go-bbs 的進度
> go-bbs 相關的實作要等 Ptt-official-app/go-bbs#82 這個完成，知道目前推文數以及修改推文數的應該直接呼叫文章屬性相關的函式就行了？

**Comment by gogog22510** [comment]
我可以幫忙這個試試看

**Comment by PichuChen** [comment]
感謝🙏再麻煩你了

**Comment by gogog22510** [comment]
想要確認一下這個issue的一些細節，我目前看到bbs那邊是統一實作了`AppendNewLine()`。所以repository的部分關於實作上下箭頭，是要直接append`\n↑`和`\n↓`就好了嗎?

**Comment by PichuChen** [comment]
> 想要確認一下這個issue的一些細節，我目前看到bbs那邊是統一實作了`AppendNewLine()`。所以repository的部分關於實作上下箭頭，是要直接append`\n↑`和`\n↓`就好了嗎?

對，可以這樣說，他基本上和推文（推噓箭頭）的動作一樣，但是在輸出顯示的時候多了一個 usefulness 的指標值

**Comment by PichuChen** [comment]
@gogog22510  想問一下這邊目前進度到哪邊了？

**Comment by gogog22510** [comment]
昨天才看到你的留言回答，我這禮拜就可以完成這個issue

**Comment by PichuChen** [comment]
> 昨天才看到你的留言回答，我這禮拜就可以完成這個issue

Ok,可以注意一下實際上的資料可能含有色碼喔

**Comment by PichuChen** [comment]
@gogog22510  想問一下這邊進度如何了？ 我感覺有些東西可能要和 @kyho4515  討論？

**Comment by kyho4515** [comment]
我目前看起來我這邊可能會需要多一個function 是根據user id, board id, filename抓到此user是否曾推過文

**Comment by gogog22510** [comment]
@PichuChen 不好意思，因為上週比較忙，所以還沒完成。
@kyho4515 請問這個method的bbs部分完成了嗎? 還是要另外開一個新的issue?

**Comment by kyho4515** [comment]
@gogog22510 Hello, 目前看起來應該是不需要了, 謝謝！

**Comment by gogog22510** [comment]
實作後發現發現了幾個困難點，我先開一個PR來追蹤
1. [bbs.DB.AppendNewline](https://github.com/Ptt-official-app/go-bbs/blob/690138360b0b0aa16166d6e5a4451fdb9a2ea890/bbs.go#L503) 需要吃boardPath，但現有的DB method裡面沒有可以得到這個路徑的函式，建議改掉bbs.DB裡的method signature
2. 我不熟悉bbs色碼，可能需要幫忙更改寫入的buf string 加入色碼
3. 不知道寫入的comment需不需要space padding? 假如需要的話需要空幾格?

**Comment by PichuChen** [comment]
1. 這個應該不用，不過我可能晚點把 go-bbs 關於 AppendNewLine 的部分重新設計，雖然現在要做可能就是當作整篇更新
2. 色碼的部分用 0x33 開頭，可以下載測試資料集，然後打開一篇有推文的文章來肝茶
3. 要，不過要查，可以看原有推文方式來做

**Comment by PichuChen** [comment]
不過 repository 應該不用考慮 2 3 兩點？

**Comment by PichuChen** [comment]
@gogog22510 你那邊能測試看看新版的 go-bbs 嗎？

**Comment by gogog22510** [comment]
好我這幾天來測試一下

**Comment by PichuChen** [comment]
@gogog22510 可以問一下目前測試結果如何嗎？

**Comment by gogog22510** [comment]
最新版本指的是github.com/Ptt-official-app/go-bbs v0.10.2 嗎? 這個版本的AppendNewLine跟development的不一樣喔

**Comment by PichuChen** [comment]
> 最新版本指的是github.com/Ptt-official-app/go-bbs v0.10.2 嗎? 這個版本的AppendNewLine跟development的不一樣喔

測試development 的

**Comment by gogog22510** [comment]
> > 最新版本指的是github.com/Ptt-official-app/go-bbs v0.10.2 嗎? 這個版本的AppendNewLine跟development的不一樣喔
> 
> 測試development 的

了解，我更新了PR，使用development版本的go-bbs

**Comment by PichuChen** [comment]
我把新的v0.11.0 推上去了，等幾分鐘再試試看，基本上和目前development 應該一樣

**Comment by gogog22510** [comment]
> 我把新的v0.11.0 推上去了，等幾分鐘再試試看，基本上和目前development 應該一樣

我更新成最新版本也解決conflict了
