### ISSUE TITLE
[BUG] 新增看板的 API 沒有回應

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#237]
### 發生了什麼事？ / The Problem
呼叫 `/v1/boards` 新增看板沒有回應

### 如何重現 / To Reproduce
1. 取得 SYSOP 的 Access Token
2. 呼叫 `curl 'http://localhost:8081/v1/boards' -d 'board_id=testboard01' -d 'title=TestBoard' -H 'Authorization: bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjQzMjc4NzUsInN1YiI6IlNZU09QIn0.8TbIOzC1wYepHprl0Bc-vhSRnAntCDlobAwyXs6-bRZ_XlUSwr3fL3CqMf6h1yg8He8drEQ3uTLIJwyUKb4d7Q' -v` 
3.  沒有回應

### 預期的行為 / Expected behavior
如果有問題的話應該也要有錯誤訊息

### 螢幕截圖 / Screenshots
![截圖 2021-06-26 下午3 48 54](https://user-images.githubusercontent.com/600238/123506300-073feb00-d696-11eb-8c8e-02e41f91b17b.png)

### 開發環境 / Environment
OS: macOS 11.4
測試集：bbs_backup_1624243644.tar.xz
Golang Version: go version go1.16.2 darwin/amd64

請參見 [PTTAPP go-BBS 後端測試表 2021060401](https://docs.google.com/spreadsheets/d/1RGIQPN6KfiCzWRQe-BeTXFUTvdwytOv0Yhd5a8ixCLk/edit#gid=0) C3-1-2

**Comment by whitefloor** [comment]
這個我來

**Comment by PichuChen** [comment]
@whitefloor 麻煩你了

**Comment by PichuChen** [comment]
![截圖 2021-07-15 下午5 48 59](https://user-images.githubusercontent.com/600238/125768019-0866b8bf-23b9-4cef-a796-a31690e236cc.png)
目前的測試結果，好像沒有顯示title ? 

@whitefloor

**Comment by whitefloor** [comment]
! 我看看

**Comment by whitefloor** [comment]
@PichuChen 
抱歉 我應該要測試的
用錯參數，已經修正了
我再重新提交一個PR

<img width="1345" alt="截圖 2021-07-15 下午8 58 21" src="https://user-images.githubusercontent.com/45685163/125792227-e684465b-b9a2-495b-92fa-89266bc5eb15.png">
