### ISSUE TITLE
[BUG] 在沒有登入時不應該取得看板設定

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#238]
### 發生了什麼事？ / The Problem
在沒有 Access Token 的前提下， GET `/v1/boards/SYSOP/information` 不應該看到看板資訊，要回傳 Error 

### 如何重現 / To Reproduce
1. 呼叫 curl 'http://localhost:8081/v1/boards/SYSOP/information'
2. 然後就看到了

### 預期的行為 / Expected behavior
應該要出現沒有權限錯誤

### 螢幕截圖 / Screenshots
![截圖 2021-06-26 下午3 55 27](https://user-images.githubusercontent.com/600238/123506467-efb53200-d696-11eb-86f5-03f653960f70.png)

### 開發環境 / Environment
OS: macOS 11.4
測試集：bbs_backup_1624243644.tar.xz
Golang Version: go version go1.16.2 darwin/amd64

請參見 [PTTAPP go-BBS 後端測試表 2021060401](https://docs.google.com/spreadsheets/d/1RGIQPN6KfiCzWRQe-BeTXFUTvdwytOv0Yhd5a8ixCLk/edit#gid=0) C3-2-2

**Comment by whitefloor** [comment]
我發現
v1/boards/{{board_id}}/information
v1/boards/{{board_id}}/settings
這兩隻api在CheckPermission裡都用PermissionReadBoardInformation裡的方法做權限檢查
<img width="866" alt="截圖 2021-06-27 下午6 00 53" src="https://user-images.githubusercontent.com/45685163/123540472-c1585500-d771-11eb-9f33-d6cce803e0ab.png">

#243 有實作檢查，會一起用到同一個方法。
這樣需要在實作新的檢查方法嗎？

**Comment by whitefloor** [comment]
附上測試結果

<img width="1343" alt="截圖 2021-06-29 下午11 05 59" src="https://user-images.githubusercontent.com/45685163/123822161-9d8e3e00-d92e-11eb-8aa4-6e57c28e9012.png">

這是我目前的執行結果，沒有token會回傳401
在 #243 實作權限檢查的時候一起被修正了

**Comment by y2468101216** [comment]
close issue 因為我修過了

**Comment by PichuChen** [comment]
@y2468101216  要Close 之前請確認問題有被修復。

目前截圖看起來他什麼都沒有回應


![截圖 2021-07-15 下午3 34 48](https://user-images.githubusercontent.com/600238/125748079-f50fe3fd-15bd-47c7-a775-e243ec9ae0d7.png)

測試的 commid-id 是 `7866d2c0c7fdb7a1af8df54317b86fe70b4d5b83`
