### ISSUE TITLE
[BUG] 取得版面設定時回傳型別錯誤

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#239]
### 發生了什麼事？ / The Problem
在 ` /v1/boards/{{board_id}}/settings` 回傳時的 false 應該是字串 `"false"`

另外這個 API 應該要有權限保護？

### 如何重現 / To Reproduce
1. curl 'http://localhost:8081/v1/boards/SYSOP/settings' 
2. 看到錯誤的資料了

### 預期的行為 / Expected behavior
回傳值應該是字串值，可能要用 fmt.Sprintf 包起來

### 螢幕截圖 / Screenshots
![截圖 2021-06-26 下午4 24 34](https://user-images.githubusercontent.com/600238/123507248-01003d80-d69b-11eb-8c29-ecc9a9a79b66.png)

### 開發環境 / Environment
OS: macOS 11.4
測試集：bbs_backup_1624243644.tar.xz
Golang Version: go version go1.16.2 darwin/amd64

請參見 [PTTAPP go-BBS 後端測試表 2021060401](https://docs.google.com/spreadsheets/d/1RGIQPN6KfiCzWRQe-BeTXFUTvdwytOv0Yhd5a8ixCLk/edit#gid=0) C3-3-1

**Comment by whitefloor** [comment]
這個我來
