### ISSUE TITLE
[BUG][後端測試表] 取得新使用者的 favorite 會出現錯誤訊息

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#258]
### 發生了什麼事？ / The Problem
取得新的使用者的最愛列表時，原先在 #235 時發現什麼都沒回傳，目前有回傳了，但是回傳的是錯誤訊息，應該要回傳空陣列才對，因為以目前狀況來說確實沒有資料的時候有可能會沒有 .fav 檔案。

這部分在 Ptt-backend 應該可以判斷出有使用者存在，但是 `.fav: no such file or directory` 的狀況，因此應該是可以直接回應空陣列給使用者，然後在 log 端加上警告。

[後端測試資料表 (2021072001)](https://docs.google.com/spreadsheets/d/1Dv0eZNTLU_NKiehR15qp8iPXAXZ85j2tWj_7h1rxUKg/edit?usp=sharing)
* C2-3-1
* C2-3-2
* C2-3-3
* C2-3-4

### 如何重現 / To Reproduce
使用 2021/7/18 的資料集，用 pichu3/123123 取得 Access Token 之後查詢 pichu3 的 favorite 會得到錯誤訊息 `pttbbs: OpenFavFile error: open ../go-bbs/home/bbs//home/p/pichu3/.fav: no such file or directory`

### 預期的行為 / Expected behavior
應該要看到
```
{"data": {"items":[]}}
```
這樣的東西

### 螢幕截圖 / Screenshots
![截圖 2021-07-31 下午12 42 28](https://user-images.githubusercontent.com/600238/127728821-849a31b9-c6e8-4665-b3e7-b08975874bf8.png)

### 開發環境 / Environment
省略
Ptt-backend: v0.0.5 (0371cfc5)

**Comment by PichuChen** [comment]
可以順便參見 Pb #235

**Comment by nickyanggg** [comment]
這個我記得已經修好了 [here](https://github.com/Ptt-official-app/go-bbs/pull/97)，應該是 go-bbs 的版本還沒更新的關係

**Comment by PichuChen** [comment]
那你要更新試試看嗎？ 目前的最新版好像測試起來還是有問題？

**Comment by nickyanggg** [comment]
我剛剛用最新 commit 版本的 go-bbs 來測試看起來是正常的
<img width="487" alt="螢幕快照 2021-07-31 下午2 14 27" src="https://user-images.githubusercontent.com/38569272/127730729-eaf68ac8-f03f-40cf-b604-211db7f22cce.png">

**Comment by PichuChen** [comment]
我覺得我抓到點了，那可以試試看幫忙把目前的 Ptt-backend的go-bbs version 拉上去之後送個PR嗎？

**Comment by nickyanggg** [comment]
可能 go-bbs 這邊需要先有新版的 release？

**Comment by PichuChen** [comment]
我把 go-bbs v0.8.0 送上去了

**Comment by nickyanggg** [comment]
@PichuChen 已升級，可能再麻煩幫忙 review 一下，另外因為 go-bbs 發文相關的函式有更動，所以升級後 ptt-backend 會有需要修改的地方，這邊暫時先以註解方式處理，可能要請 @y2468101216 等 merge 以後順便在這個 [pr](https://github.com/Ptt-official-app/Ptt-backend/pull/251) 處理。
