### ISSUE TITLE
[BUG][後端測試表] 取得新使用者的 draft 會有錯誤

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#260]
### 發生了什麼事？ / The Problem
請參考 #258 ，在使用者沒有 draft 的時候應該要表現出使用者沒有 draft 而不是出現錯誤

請參考後端測試表 C2-7-2

### 如何重現 / To Reproduce
1. 登入 pichu3 並且取得 Access Token
2. 取得 draft0
3 看到錯誤 `open ../go-bbs/home/bbs//home/p/pichu3/buf.0: no such file or directory`

### 預期的行為 / Expected behavior
應該要如文件看到空的 draft

### 螢幕截圖 / Screenshots
![截圖 2021-07-31 下午1 09 09](https://user-images.githubusercontent.com/600238/127729356-28ecba2c-cb9f-429f-9579-e160acd788fd.png)

### 開發環境 / Environment
略
Ptt-backend: v0.0.5 (0371cfc5)

**Comment by nickyanggg** [comment]
這 issue 應該在上面那個 pr 就修好了 (附上測試截圖)
<img width="796" alt="螢幕快照 2021-08-07 下午10 19 14" src="https://user-images.githubusercontent.com/38569272/128603274-e545492a-3fb1-4523-8369-4d07ee962b3f.png">

**Comment by y2468101216** [comment]
@PichuChen 這個 issue 是否可以關閉，我測試也是相同結果
<img width="566" alt="截圖 2021-08-13 上午9 52 59" src="https://user-images.githubusercontent.com/10670845/129293791-f94a68e7-c6d2-435c-930d-da172e004469.png">

**Comment by PichuChen** [comment]
有用新的帳號嗎？試試看pichu3 因為如果說像是SYSOP或是pichu並不會觸發這個bug，或是我晚點重新測試

**Comment by y2468101216** [comment]
上面 nickyanggg 就是用 pichu3

**Comment by PichuChen** [comment]
那我這週再試試看pichu3

**Comment by PichuChen** [comment]
pichu3 測試正常 
<img width="1020" alt="截圖 2021-08-21 下午2 34 29" src="https://user-images.githubusercontent.com/600238/130313015-a84cb0e6-5701-4c1c-9e7a-bb349a204126.png">
