### ISSUE TITLE
[BUG][後端測試表] 取得看板列表時 moderators 沒有正常顯示

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#266]
### 發生了什麼事？ / The Problem
看板列表的版主列表有問題

### 如何重現 / To Reproduce
1. 登入 SYSOP
2. 透過 GET /v1/boards 取得看板列表後就會看到有問題了

### 預期的行為 / Expected behavior
沒版主的狀況應該是空陣列
有版主的狀況應該要有看到看板版主
SYSOP看板的版主通常是SYSOP

### 螢幕截圖 / Screenshots
![截圖 2021-08-07 下午7 28 50](https://user-images.githubusercontent.com/600238/128598680-27b6135c-918d-4335-b6d0-59a99adb1752.png)

### 開發環境 / Environment
Ptt-backend: 6bf9e57c9079b7cda312e03b4052c2da2b1bc6ee
請參考測試表 C3-1-3 C3-2-3

**Comment by nickyanggg** [comment]
這邊應該有板主的狀況時回傳會正確，無板主時因為 go-bbs 那邊是直接回傳 strings.split 的結果，所以會回傳 `[]string{""}` 導致結果錯誤，已發 pr 修正

**Comment by PichuChen** [comment]
go-bbs 更新的 v0.11.0 應該就 OK 了。
