### ISSUE TITLE
[BUG] pttapp.cc/swagger 502 Bad Gateway

### ISSUE THREAD

**Issue by karta0807913** [Ptt-official-app/Ptt-backend#267]
### 發生了什麼事？ / The Problem

[pttapp.cc/swagger](https://pttapp.cc/swagger/#/%E4%BD%BF%E7%94%A8%E8%80%85%E9%83%A8%E5%88%86/post_v1_token) 沒有正常回應

### 如何重現 / To Reproduce

正常的 swagger

### 螢幕截圖 / Screenshots

![](https://i.imgur.com/t1E4DCM.png)

**Comment by PichuChen** [comment]
用 `docker-compose up` 把它開起來了

有辦法讓他變成 daemon 嗎？
![截圖 2021-08-15 上午3 31 15](https://user-images.githubusercontent.com/600238/129458212-66587d9e-af84-40fa-a91a-06efba4aab69.png)

**Comment by karta0807913** [comment]
`docker-compose -d up` 看看
