### ISSUE TITLE
[建議] 希望可以使用 Dockerfile 來建置環境

### ISSUE THREAD

**Issue by karta0807913** [Ptt-official-app/Ptt-backend#269]
### 原本作法的問題 / Existed Problem

目前這個專案的 docker-compose.yml 中只有 swagger 的設定，希望也可以建立這個專案的 image

### 實作細節 / Details of Implement
建立起 Dockerfile

### 期程 / Schedule
幾小時？

**Comment by PichuChen** [comment]
Docker 的範圍要抓清楚一下目的，因為目前我覺得 go build 的編譯方式其實就很好用了

然後 Docker 的作法最大的缺點是目前 SHM 可能會不支援，以及還不確定在 M1 上的支援程度。

**Comment by karta0807913** [comment]
我是覺得這個專案目前現在缺少一個「開箱即用」的腳本，而 Docker 可以很好的做到這一點。
剛入門的開發者只需要執行 `docker build` 與 `docker run` 便可以建立起一個可以使用的環境，不需要關心到底下載了哪些設定檔。
Apple M1 的部份我不太確定到底有沒有問題，不過據官方的[說明](https://docs.docker.com/desktop/mac/apple-silicon/)只要 image 有 ARM 發行版就可以使用。
另外 shm 的部份我不太清楚，請問有可以測試的方法嗎？

**Comment by PichuChen** [comment]
但是我目前電腦是沒有docker的，另外是docker雖然可以加速安裝以及deploy，但是在開發上面似乎沒有比較便利？

SHM 的部分可以先不用管他。
