### ISSUE TITLE
[BUG] can not reproduce https://pttapp.cc

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/Ptt-backend#27]
### 發生了什麼事？ / The Problem

https://github.com/Ptt-official-app/Ptt-backend/blob/development/FOR_DEVELOPERS.md#deploy-%E5%88%B0-staging-%E7%92%B0%E5%A2%83%E4%BB%A5%E5%8F%8A%E6%AD%A3%E5%BC%8F%E7%92%B0%E5%A2%83%E7%9A%84%E6%96%B9%E6%B3%95
提到 development site 是 https://pttapp.cc

目前看起來 https://pttapp.cc 是使用跟 https://term.ptt.cc 類似的方式跟既有的 pttbbs 站相連.

### 如何重現 / To Reproduce

按照以下 link 無法產生跟 https://pttapp.cc 一樣的結果.

https://github.com/Ptt-official-app/Ptt-backend/blob/development/FOR_DEVELOPERS.md#%E5%AE%89%E8%A3%9D%E8%88%87%E8%A8%AD%E5%AE%9A

**Comment by PichuChen** [comment]
目前 FOR_DEVELOPMENT.md 上面提供的是靜態資料，不是和 BBS 站直接連動的動態資料。
然後現在也還沒有提供 VT-100 介面，所以沒辦法用 SSH, Telnet 或者是 WebSocket 連線是正常的。

如果想要增加靜態資料的內容，可以在 pttapp.cc 上面新增文章之類的。
如果想要測試實際 API 連結動態資料的結果，可以直接對 https://pttapp.cc/v1/token ... 下 Request ，在這邊如果新增文章的話會即時看到 API 抓回的內容有變動。
