### ISSUE TITLE
[BUG] C5-1-3: GET /v1/boards/test/articles 搜尋推文應該要出現「來測試看看轉錄看板文章」這篇文章

### ISSUE THREAD

**Issue by karta0807913** [Ptt-official-app/Ptt-backend#279]
### 發生了什麼事？ / The Problem

在放入 Access Token 的情況下在 GET /v1/boards/test/articles?recommend_count_gt=2 應該要出現「來測試看看轉錄看板文章」這篇文章

### 如何重現 / To Reproduce

```
curl -H 'Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzAyMjA4NTMsInN1YiI6IlNZU09QIn0.fvNBqI4SfRGCmMY0Rk56Yp1efgxnbFIHcpZ6HWBZMNvfNvUR4PZIS72efjjddKmjn94MDQ1l40LcZI2_l3LHvg' \
localhost:8081/v1/boards/test/articles?recommend_count_ge=2
```

### 預期的行為 / Expected behavior
出現「來測試看看轉錄看板文章」這篇文章

### 螢幕截圖 / Screenshots
出現所有文章

### 開發環境 / Environment
- OS: ubuntu:20.04
- Golang Version: go version go1.16.6 linux/amd64

**Comment by karta0807913** [comment]
@PichuChen 這邊我看了一下原始碼，我發現它裡面所定義的變數為 `recommend_count_ge` 而非 `recommend_count_gt`。
當我使用變數 `recommend_count_ge` 的時候這個功能是正常的。

![](https://i.imgur.com\/tGb3lXb.png)

https://github.com/Ptt-official-app/Ptt-backend/blob/db1d8a2e372692c1c3d917212857773441c88cf3/internal/delivery/http/route_boards_articles.go#L34-L37

**Comment by PichuChen** [comment]
所以應該是要增加支援 _gt 嗎？

**Comment by karta0807913** [comment]
這我不確定，現在應該要把 `_ge`改成 `_gt` 還是多加一個 `_gt` 參數以符合測試？
要看當時規格怎寫的吧？

**Comment by karta0807913** [comment]
因為照字面上意思 `_gt` 是 `greater then` 所以在字面理解上理應不會出現「來測試看看轉錄看板文章」這篇文章（因為推薦次數為2）。
所以我建議應該修改測試表中的 `_gt` 為 `_ge`，如此一來指定推薦次數時為2時才會出現「來測試看看轉錄看板文章」這篇文章。

**Comment by PichuChen** [comment]
確實 _ge 可以，不過文件裡面是有要求實作 _gt 的

![截圖 2021-09-04 下午9 49 42](https://user-images.githubusercontent.com/600238/132096714-fa0f458a-78b8-434e-bf22-83b5176cd58d.png)

https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.bnhpxsiwnbey

**Comment by karta0807913** [comment]
那是不是應該修改內文為
「在放入 Access Token 的情況下在 GET /v1/boards/test/articles?recommend_count_gt=<span style="color:red">_**1**_</span> 應該要出現「來測試看看轉錄看板文章」這篇文章」

或是新增另一篇文章，例如「來測試推薦數搜尋」，並且他的的推薦數為三？

>

**Comment by PichuChen** [comment]
我覺得應該是程式碼有實作 _gt 就行了？

**Comment by y2468101216** [comment]
@karta0807913 有興趣幫忙實作 gt 跟 lt 嗎 我看這兩個都沒實作

**Comment by karta0807913** [comment]
@y2468101216 我提交了一個 pull request #290
還請確認看看是不是與你預期的一樣
