### ISSUE TITLE
[BUG] C6-1-2: 新增推文時沒有回應，出現 HTTP 500 Server Error

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#284]
### 發生了什麼事？ / The Problem
發生了 Server Error 但是 Server 卻沒有出現相關Log，懷疑錯誤處理被吃掉了。

### 如何重現 / To Reproduce
請參考 testing-script C6-1-2.sh
1. 取得可以在 test 版發文的 Access Token
2. 找到最新一篇文章的 filename
3. 用`curl -v http://localhost:8081/v1/boards/test/articles/$NEW_FILENAME -d 'action=append_comment'  --data-urlencode 'type＝推' --data-urlencode 'text=test push'` 發送新推文，接著就會看到錯誤了

### 預期的行為 / Expected behavior
應該要如文件回應被推文的文章內容

### 螢幕截圖 / Screenshots
伺服器端：
![截圖 2021-09-05 下午11 29 00](https://user-images.githubusercontent.com/600238/132132297-1ccbc866-b300-4929-a0da-86f6693f753e.png)

客戶端：
![截圖 2021-09-05 下午11 29 34](https://user-images.githubusercontent.com/600238/132132326-6cd1e70a-bb7e-4d4c-ae16-9c3b09414eb1.png)

### 開發環境 / Environment
Package version: cb8fb31f7a480dce1f29406be6c6d215d365c37e

**Comment by y2468101216** [comment]
這是因為 go-bbs 裡的 AppendBoardArticleFile 並沒有使用 board_id 去取 path 所以必須要改 go-bbs 那邊

**Comment by PichuChen** [comment]
@y2468101216 那你可以幫忙開一下ISSUE嗎？

**Comment by y2468101216** [comment]
@PichuChen 我想先在這邊討論一下再開 issue

**Comment by kyho4515** [comment]
我試了一下, 問題好像是C6-1-2.sh裏, `type＝推`的＝打成全寫
雖然改好後還是有其他問題就是了

server端
<img width="581" alt="Screen Shot 2021-09-09 at 10 50 33 PM" src="https://user-images.githubusercontent.com/10025955/132791595-6a37e44c-a87e-4c62-a60e-1b25fb3fb252.png">
client端
<img width="1000" alt="Screen Shot 2021-09-09 at 10 50 54 PM" src="https://user-images.githubusercontent.com/10025955/132791618-22b67369-a432-451c-a5d1-253e56c12194.png">

另外, 新增推文的PR還沒merge #268 
還有我們code裡type是用上下箭頭, `type=↑`

再補充一點, 推文的post要放access token, 再來就進到還沒merge的部分了

**Comment by PichuChen** [comment]
> 我試了一下, 問題好像是C6-1-2.sh裏, `type＝推`的＝打成全寫
> 雖然改好後還是有其他問題就是了

感謝提醒，把這個修正推上去了
