### ISSUE TITLE
[BUG] C6-1-7, C6-1-8: 轉發文章時出現 path not found

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#286]
### 發生了什麼事？ / The Problem
path /v1/boards/test/articles/M.1629565994.A.158 not found

有可能需要分成兩個 ISSUE 來解？

搞不好成因和無法刪除的 #285  類似

### 如何重現 / To Reproduce
請參考 testing-script C6-1-7 C6-1-8
1. 利用 SYSOP 權限取得 Access Token
2-a. 將 SYSOP 中最新一篇文章轉到 test 版 (`curl http://localhost:8081/v1/boards/test/articles/$NEW_FILENAME -d 'action=forward_article'  --data-urlencode 'board_id=test' `)
2-b. 將 SYSOP 中最新一篇文章轉到自己的信箱 （`curl http://localhost:8081/v1/boards/test/articles/$NEW_FILENAME -d 'action=forward_article'  --data-urlencode "email=$1"`）

然後就出現 not found 了

### 預期的行為 / Expected behavior
要能正常轉文

### 螢幕截圖 / Screenshots
![截圖 2021-09-05 下午11 50 14](https://user-images.githubusercontent.com/600238/132133085-8e0e72f3-e496-4997-9cd4-a9656fcec402.png)

### 開發環境 / Environment
Package version: cb8fb31f7a480dce1f29406be6c6d215d365c37e

**Comment by karta0807913** [comment]
@PichuChen 我試著修了一下，還請幫我 code review 看看哪裡有問題
