### ISSUE TITLE
[BUG] C7-1-1: 熱門文章 API 沒有回應任何文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#287]
### 發生了什麼事？ / The Problem
原定上限100個文章的熱門文章 API 沒有回應任何文章

如果是剛啟動的伺服器，應該也是要掃描一下現有的文章列表來產生熱門文章快取？

### 如何重現 / To Reproduce
1. 取得使用者權限
2. 使用 `curl -s http://localhost:8081/v1/popular-articles -H "Authorization: bearer $ACCESS_TOKEN"` 取得目前熱門文章

然後就會發現回傳空陣列了

### 預期的行為 / Expected behavior
要有文章

### 螢幕截圖 / Screenshots
![截圖 2021-09-06 上午12 05 51](https://user-images.githubusercontent.com/600238/132133540-660b4cae-3b6c-4d81-94d7-e1aa48d6fed4.png)

### 開發環境 / Environment
Package version: cb8fb31f7a480dce1f29406be6c6d215d365c37e

**Comment by y2468101216** [comment]
![截圖 2021-09-08 下午2 45 19](https://user-images.githubusercontent.com/10670845/132459778-af25451f-2ec2-4107-8649-95e4fd9d078a.png)

**Comment by y2468101216** [comment]
我看是有文章的？

**Comment by PichuChen** [comment]
你取的是看板的API

**Comment by y2468101216** [comment]
目前看起來 [GetPopularArticles](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/article.go#L28) 

沒有實作，有意願實作歡迎參考文件實作
