### ISSUE TITLE
[建議] logger增加debug level的功能

### ISSUE THREAD

**Issue by tanyeun** [Ptt-official-app/Ptt-backend#29]
### 原本作法的問題 / Existed Problem
目前所有的logger message都會直接print出來
Example
![image](https://user-images.githubusercontent.com/22489112/106622505-a14fab80-65ae-11eb-8974-41e96c4477f1.png)

### 實作細節 / Details of Implement
跟 @PichuChen 稍微討論過了一下，有兩種做法
一個是在main那邊加上可以吃command line option的架構
我個人是比較喜歡這種作法，因為很適合習慣用command line的開發者使用
而且彈性會比在config file裡面加參數來得彈性

初步想法是:

./Ptt-backend --logLevel debug
./Ptt-backend --logLevel Warning
... 分別對應
![image](https://user-images.githubusercontent.com/22489112/106623586-bd078180-65af-11eb-8f7b-a18a9ad264db.png)
如果是設成
./Ptt-backend --logLevel Error
那麼只會印出:
logger.Errorf
logger.Criticalf
logger.Alertf
logger.Emergencyf

如果是設成
./Ptt-backend --logLevel Alert
那麼只會印出:
logger.Emergencyf

另一種做法是在config_default.toml裡面多加一個參數

應該屬於低難度適合新手的(比如我XDDD)
估計一個人一個周末一定可以弄出來

**Comment by rainlay** [comment]
可以加在類似環境變數檔案的地方如 config.toml, 也相應簡單直覺，

如果以後有不同的測試環境，可以於 ci/cd 或 env 設定不同的 log level。(當然在 go build 加入 flag 也是能達到相同效果)

**Comment by tanyeun** [comment]
相關討論 #21

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？

**Comment by karta0807913** [comment]
我在 #272 試著實做了一下這篇所說的內容，需要請各位幫我看一下是不是各位所期望的內容/行為
