### ISSUE TITLE
Project Layout

### ISSUE THREAD

**Issue by mkfsn** [Ptt-official-app/Ptt-backend#3]
FYI: https://github.com/golang-standards/project-layout

**Comment by PichuChen** [comment]
具體的話有哪些檔案要移動到哪邊嗎？

**Comment by mkfsn** [comment]
@PichuChen 以現在的 code 的話我會傾向這樣放：

```
├── cmd
│   └── main.go
├── configs
│   └── config_default.toml
├── go.mod
├── go.sum
├── internal
│   ├── config
│   │   └── config.go
│   ├── logger
│   │   └── logger.go
│   └── usecases
│       ├── permissions.go
│       ├── route_boards.go
│       ├── route_boards_treasures.go
│       ├── route_borads_articles.go
│       ├── route_classes.go
│       ├── route_token.go
│       ├── route_users.go
│       └── route_users_test.go
└── web
    └── route.go
```

我會想把主要的 business logic 搬到 /internal/usecases 底下，把他跟 web (RESTful API server) 分開，這樣之後要加 gRPC 甚至是 GraphQL 的話，理論上應該可以跟 usecase 完全分離，不用改太多 usecase 的 code 才對。

其他的比較 minor 不過我覺得蠻 common sense，像是 binary (main package) 放在 /cmd 底下，logger, config 放到 /internal 底下。

不過或許有更好的擺法，歡迎討論～


BTW 我看到 route 有分 /v1 所以或許我們  /internal/usecases 也可以細分 /internal/usecases/v1 之類的。

**Comment by PichuChen** [comment]
Golang 的分資料夾和其他語言例如 JS 或是 C 的分資料夾有不太一樣的意義，分資料夾後的不同程式碼彼此之間的關係會像是不同Package一樣，不容易直接互相呼叫喔。

**Comment by mkfsn** [comment]
> Golang 的分資料夾和其他語言例如 JS 或是 C 的分資料夾有不太一樣的意義

@PichuChen 我的理解是那些都是不同的用途。舉例來說， config 是專門提供 config 用的，在 #2 也有提到我們可以把 third-library 另外切開來，這樣之後如果要 support YAML 的 config 的話就是在 config package 解決。

另外一個例子，logging 專門處理要怎麼實現 logging ，因為現在可能很簡單的把 loggging output 到 std 但是之後可能會要寫到檔案或者是寫到其他地方，這些都是跟 "PTT web RESTful API" 的邏輯無關的，所以我覺得把它們搬到獨立的 package 是合理的。

**Comment by PichuChen** [comment]
如果以 log 的例子來說的話，那這樣所有的檔案都需要 import "https://github.com/Ptt-official-app/Ptt-backend/internal/logger" 了，然後 Logger 裡面也幾乎所有的 function 都必須要被 export 出來？

**Comment by mkfsn** [comment]
> 如果以 log 的例子來說的話，那這樣所有的檔案都需要 import "https://github.com/Ptt-official-app/Ptt-backend/internal/logger" 了，然後 Logger 裡面也幾乎所有的 function 都必須要被 export 出來？

我想這要看應用，跟怎麼切資料夾應該無關。 #4 我做了一個 logging package 然後它有提供一個 NewLogger function， 這樣 main package own 一個 logger (跟現在一樣)，所以其他檔案還是不需要去 import "github.com/Ptt-official-app/Ptt-backend/internal/logger"。當然如果是要 centralized logger 的話，就會是像你說的那樣沒錯。

**Comment by PichuChen** [comment]
這樣的話好像可以，另外我有查到 internal package 好像有特殊意義？

https://golang.org/doc/go1.4#internalpackages

我先前確實沒有特別注意到 internal 有特別作用，如果是這樣的話其實把 logger 等等的放入 internal ，然後再把主要物件放在 global 寫在 main.go 的話應該 OK?

看其他人有沒有意見？

**Comment by mkfsn** [comment]
> 這樣的話好像可以，另外我有查到 internal package 好像有特殊意義？
> 
> https://golang.org/doc/go1.4#internalpackages
> 
> 我先前確實沒有特別注意到 internal 有特別作用，如果是這樣的話其實把 logger 等等的放入 internal ，然後再把主要物件放在 global 寫在 main.go 的話應該 OK?
> 
> 看其他人有沒有意見？

那滿舊的了 (go 1.4 XD) 但我沒印象中有被強制限制這樣（或許有只是我不曉得），不過我覺得 internal 合理是因為我們應該不打算 export 這個 repo 的任何 API 給其他 project 使用，所以放進 internal 的東西是對這個 repo 而言是 private 的。有些情況會需要讓其他 project 使用的話，會放到 /pkg 底下。

---

順帶一提，我覺得切 package 的一個好處是方便做 unit test。舉例來說，這個 test:
https://github.com/Ptt-official-app/Ptt-backend/blob/main/route_users_test.go#L53-L90

的用意只是要測試今天我戳 /v1/users 的時候 response 會不用有：

https://github.com/Ptt-official-app/Ptt-backend/blob/main/route_users.go#L68-L82

那其實我們把 web (RESTful) 跟 usecase 分開的話，理論上我可以寫的 unit test 去測試 `func GetUsers() map[string]interface{}` 這個 function (BTW 我覺得那個 struct 應該要訂好，而不是用 interface{}) ，好處是我把 protocol 跟 business-logic 切開了，這樣之後我可以加 protocol 然後都是去呼叫同一個 function (GetUsers)，test 也比較好寫（但可能需要用一點 DI ，譬如有要 mock database layer 的情況），再者我不覺得現在 route_users_test.go 的 testcase 按照 
![image](https://user-images.githubusercontent.com/667169/105203197-cdfece80-5b7d-11eb-85b7-906efbc88a2b.png)
的分法算是 unit-test。

**Comment by Min-Feng** [comment]
> @PichuChen 以現在的 code 的話我會傾向這樣放：
> 
> ```
> ├── cmd
> │   └── main.go
> ├── configs
> │   └── config_default.toml
> ├── go.mod
> ├── go.sum
> ├── internal
> │   ├── config
> │   │   └── config.go
> │   ├── logger
> │   │   └── logger.go
> │   └── usecases
> │       ├── permissions.go
> │       ├── route_boards.go
> │       ├── route_boards_treasures.go
> │       ├── route_borads_articles.go
> │       ├── route_classes.go
> │       ├── route_token.go
> │       ├── route_users.go
> │       └── route_users_test.go
> └── web
>     └── route.go
> ```

就我個人認知
web 資料夾應該是放 html 或 相關圖片
之類的資源檔案

個人的話會想要 
依照 六邊形架構 整潔架構分為 四個水平分平
然後依照 go 的推薦寫法 
使用垂直分層 切割不同 業務功能

[六邊形架構介紹](https://herbertograca.com/2017/09/14/ports-adapters-architecture/?fbclid=IwAR3e--s4t2woKABzoMUb9PXS27ecrbq6ysxb9YkGS5HkvJ3tQP_ZO76M1QA)

![](https://i.imgur.com/N1eGqKz.png)

- driving adapter(user interface)
- application (use case)
- domain
- driven adapter(infra)

然後在另外 開一個資料夾 tool
底下放 config log 的資料夾
放一些 與 bbs 業務邏輯 無關的 pkg

但我怕太複雜
畢竟不是所有人都懂 整潔架構

如果我的文字描述不夠好
可以看我寫的簡易範例
[ddd example](https://github.com/Min-Feng/iGoStyle)

有注意到
現在的寫法 沒有使用 介面 interface
似乎不容易做測試
不知道之後有打算修改嗎？

**Comment by mkfsn** [comment]
> 就我個人認知
> web 資料夾應該是放 html 或 相關圖片
> 之類的資源檔案
>
> 雖然我沒在用 internal
> 一律放 pkg

阿感謝指出，我就感覺哪裡怪怪的 XD 那應該就是所有都塞 internal ，畢竟對 ptt 而言並沒有打算讓任何 package 是 public 的（至少現階段來說是這樣？）


> 還沒開始看 相關專案的實際內容
> 但感覺這個 go-bbs 專案
> 似乎算 infra 層, 實際對接哪些 bbs

我的理解是那會類似 database/sql package，是算 infra 那邊沒錯，應該可以直接把它當作 repository layer 的東西來使用（參考[這篇](https://github.com/bxcodec/go-clean-arch)）



> 有注意到
> 現在的寫法 沒有使用 介面 interface
> 似乎不容易做測試
> 不知道之後有打算修改嗎？

我覺得這也是跟改 Project Layout 有關耶，現在東西都在 main package 就算你有 interface 也沒得測試 XD #4 我把 logger 拉出去之後就順便加了 interface ，當然我們應該不太會需要 test logger 就是了 ...

**Comment by PichuChen** [comment]
logger (logging) 的部分在 #4 移動完了，config.go 雖然也是只有單個檔案不過也有要處理嗎？還是另外的 ISSUE 討論？

另外是按照 internal 的標準， web/route 不確定能不能 access 到 internal/usecase 喔？

**Comment by KScaesar** [comment]
> 另外是按照 internal 的標準， web/route 不確定能不能 access 到 internal/usecases 喔？

我以為之前的討論
有解釋 web 目錄, 不會放 go 程式碼
route.go 我覺得要放 internal 內部
在外面的話 應該是無法 access

我可能會
在 internal 目錄 建立一個 http 或 api 的目錄
把 route.go 放在其中

**Comment by PichuChen** [comment]
https://github.com/Ptt-official-app/Ptt-backend#%E8%B3%87%E6%96%99%E5%A4%BE%E7%B5%90%E6%A7%8B

提醒一下，這邊可能也要修改
