### ISSUE TITLE
[建議] RESTFul API 文件轉移至swagger上維護

### ISSUE THREAD

**Issue by TimoChiang** [Ptt-official-app/Ptt-backend#30]
### 原本作法的問題 / Existed Problem

（跟#5 的內容有點不一樣所以另外開了一個issue想跟大家討論）
目前RESTful API列表在Google Docs「[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx)」上維護，在查找時稍微有點不方便。

### 實作細節 / Details of Implement

看了一下內容似乎可以寫進swagger裡面，除了介面較清楚之外也比Google Docs來的好管理版本。

目前的想法是，把原文件內容手動轉成swagger的格式檔案，然後把該檔案在放在本repo中維護。
開發時可以藉由docker在localhost查看swagger檔案所生成的API列表，方便開發時查找API與修改內容。
（暴力一點直接把檔案內容丟到[Swagger Editor](https://editor.swagger.io/)上看也是一種做法XD...）
我知道有自動生成的套件但沒有使用過，如果有經驗的人評估可行的話也是OK。
有其他更好的想法也歡迎提出！

另外自己目前的經驗大部分都是使用yaml檔，要採用yaml還是json的優缺點我並不太清楚。
歡迎大家提供意見！

### 期程 / Schedule

討論完後應該1周左右可以完成？

### 相關文件 / Documents
[swagger文檔](https://swagger.io/docs/specification/about/)

**Comment by PichuChen** [comment]
有其他人有興趣跳這個坑嗎？ 看起來一開始要先切在另外的 Branch

**Comment by DeanXu2357** [comment]
我來幫忙

**Comment by wagaru** [comment]
還需要人力的話我也可以幫忙~😀

**Comment by sageofcross** [comment]
看起來是要手動編寫 Swagger 文件而非透過套件來自動產生嗎？

可能有的問題是 Code 修改後忘了改對應 Swagger 規格，這點在未來 Review 時要注意 XD

**Comment by PichuChen** [comment]
> 我來幫忙



> 還需要人力的話我也可以幫忙~😀

我先把 ISSUE Assign 給 @DeanXu2357 完成之後再請 @wagaru 和 @TimoChiang 幫忙 review?

**Comment by TimoChiang** [comment]
> 看起來是要手動編寫 Swagger 文件而非透過套件來自動產生嗎？

稍微查了一下套件的部分([go-swagger/go-swagger](https://github.com/go-swagger/go-swagger)、[swaggo/swag](https://github.com/swaggo/swag)）
考慮到以下幾點：
- 依照目前的route設計試了一下套件，好像沒辦法正常生成，為了這個改設計感覺不妥
- 自動生成的內容可能還是有它的侷限，沒辦法涵蓋全部
- 目前穩定的套件還是只支援到swagger 2.0(OpenAPI 2.0)，想採用較新的OpenAPI 3.0

似乎還是手動比較適合～

> 可能有的問題是 Code 修改後忘了改對應 Swagger 規格，這點在未來 Review 時要注意 XD

這就靠大家一起幫忙維護了XD

既然看起來大家沒意見的話，我提議一下規格：

- 檔案格式：`yaml`
- swagger版本：OpenAPI 3.0

沒問題的話就拜託 @DeanXu2357 囉～

**Comment by chhsiao1981** [comment]
可參考以下方式移至 swagger 上維護.

https://api.devptt.site:8080/

https://github.com/Ptt-official-app/go-pttbbs/tree/main/apidoc

**Comment by PichuChen** [comment]
如果直接複製貼上 @chhsiao1981  有可能會有違反 GPL 的問題。

然後避免時程過久風險較大的問題，可以先從小部分開始，例如開一個子 ISSUE 然後關聯指回這個主 ISSUE，然後子 ISSUE 可能只有實作 TOKEN 這個 API 的 YAML 這樣，那一個完成之後就可以有人幫忙把所有 API Endpoint 的子 ISSUE 都開立起來，接著就能在 Slack 宣傳讓新手試試看依樣畫葫蘆來實作。
