### ISSUE TITLE
[建議] golang code style

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#38]
### 原本作法的問題 / Existed Problem
目前 CI 有跑 golangci-lint 可能需要 code style，例如 : 

1. 官方庫提供的 function err 要不要接(ex: json.Unmarshal)
2. 要不要全面跑 go fmt，強烈建議要

### 實作細節 / Details of Implement
1. 在專案底下增加 .golangci.yaml
2. ci cd 自動執行 go fmt
3. go mod add golangci-lint 

### 期程 / Schedule
- 討論時間： 到過年後，2/22
- 實作時間： 一天
- 確認時間：一天 

### 相關文件 / Documents
https://golangci-lint.run/

**Comment by Julian-Chu** [comment]
go fmt是為了檢查的話 golangci 的檢查就包含了
是為了排版的話，那要考慮在git hook跑

**Comment by Julian-Chu** [comment]
go mod安裝golang-ci不是推薦的方式
![image](https://user-images.githubusercontent.com/7224544/107005837-95234400-6790-11eb-81db-f82448bfdebb.png)

**Comment by y2468101216** [comment]
> go mod安裝golang-ci不是推薦的方式
> ![image](https://user-images.githubusercontent.com/7224544/107005837-95234400-6790-11eb-81db-f82448bfdebb.png)

有道理，那改為使用 binary?

然後我看 golang-ci 不是預設會跑 go fmt。

**Comment by Julian-Chu** [comment]
> 
> 有道理，那改為使用 binary?
> 
> 然後我看 golang-ci 不是預設會跑 go fmt。

更新一下，目前make.bash(跟CI)都是用binary， make.bat是用go get

golang-ci 預設跑的是gofmt -s 只用於檢查，不會改變原來的檔案， 而且排版後也要commit，所以我會建議可以給git hook做排版

**Comment by PichuChen** [comment]
go fmt 的問題應該是 commit 之前通常 IDE 都會跑？

**Comment by Julian-Chu** [comment]
> go fmt 的問題應該是 commit 之前通常 IDE 都會跑？

這個取決於每個人的開發環境設定摟，除非我們把設定也加到到git裡，不然這個不能保證IDE或是editor一定會跑(同時還要考慮不同開發環境)，git hook會比較通用
至於現行go fmt，有CI後 會在PR/push的時候抓出來沒做gofmt,  format後push一次就好了，就是developer要多花一點點功夫這樣

**Comment by PichuChen** [comment]
> > go fmt 的問題應該是 commit 之前通常 IDE 都會跑？
> 
> 這個取決於每個人的開發環境設定摟，除非我們把設定也加到到git裡，不然這個不能保證IDE或是editor一定會跑(同時還要考慮不同開發環境)，git hook會比較通用
> 至於現行go fmt，有CI後 會在PR/push的時候抓出來沒做gofmt, format後push一次就好了，就是developer要多花一點點功夫這樣

我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。

**Comment by Julian-Chu** [comment]
> 
> 我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。

那就維持原狀，反正PR時候lint錯誤就請作者設定gofmt後，重新push就好。
有人願意分享開發環境的gofmt設定可以放在FOR_DEVELOPERS.md，repo本身就不做自動gofmt的設定，這樣如何?

**Comment by PichuChen** [comment]
> > 我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。
> 
> 那就維持原狀，反正PR時候lint錯誤就請作者設定gofmt後，重新push就好。
> 有人願意分享開發環境的gofmt設定可以放在FOR_DEVELOPERS.md，repo本身就不做自動gofmt的設定，這樣如何?

分享開發環境的設定我有點不懂，因為 gofmt 我印象中他就是一個命令，還是你的意思是各個 IDE 如何設定 gofmt?

**Comment by Julian-Chu** [comment]
> > > 我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。
> > 
> > 
> > 那就維持原狀，反正PR時候lint錯誤就請作者設定gofmt後，重新push就好。
> > 有人願意分享開發環境的gofmt設定可以放在FOR_DEVELOPERS.md，repo本身就不做自動gofmt的設定，這樣如何?
> 
> 分享開發環境的設定我有點不懂，因為 gofmt 我印象中他就是一個命令，還是你的意思是各個 IDE 如何設定 gofmt?

對，我以為是要討論各個IDE自動用gofmt排版的部分

**Comment by PichuChen** [comment]
> > > > 我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。
> > > 
> > > 
> > > 那就維持原狀，反正PR時候lint錯誤就請作者設定gofmt後，重新push就好。
> > > 有人願意分享開發環境的gofmt設定可以放在FOR_DEVELOPERS.md，repo本身就不做自動gofmt的設定，這樣如何?
> > 
> > 
> > 分享開發環境的設定我有點不懂，因為 gofmt 我印象中他就是一個命令，還是你的意思是各個 IDE 如何設定 gofmt?
> 
> 對，我以為是要討論各個IDE自動用gofmt排版的部分

如果是這樣的話那應該是要另外開 ISSUE, 然後修改 FOR_DEVELOPERS.md 增加教學。雖然現階段因爲人數還沒有那麼多，所以請有問題的人到 Slack 發問我們應該還能負擔？

**Comment by Julian-Chu** [comment]
> > > > > 我覺得 go fmt 要不要加比較不用討論，因為目前 golang 社群應該沒有反對意見才是，無論在哪個階段所有的 Golang 開發者基本上都會同意 go fmt 跑出來的 Coding style，只不過是會不會加了之後變成在開發上發生麻煩，舉例來說，假如有人他只是要更新開發文件的 README，然後沒有安裝 go 的環境，於是就被 hook 卡死沒辦法 git push 了，之類的。
> > > > 
> > > > 
> > > > 那就維持原狀，反正PR時候lint錯誤就請作者設定gofmt後，重新push就好。
> > > > 有人願意分享開發環境的gofmt設定可以放在FOR_DEVELOPERS.md，repo本身就不做自動gofmt的設定，這樣如何?
> > > 
> > > 
> > > 分享開發環境的設定我有點不懂，因為 gofmt 我印象中他就是一個命令，還是你的意思是各個 IDE 如何設定 gofmt?
> > 
> > 
> > 對，我以為是要討論各個IDE自動用gofmt排版的部分
> 
> 如果是這樣的話那應該是要另外開 ISSUE, 然後修改 FOR_DEVELOPERS.md 增加教學。雖然現階段因爲人數還沒有那麼多，所以請有問題的人到 Slack 發問我們應該還能負擔？

好啊，因為我覺得gofmt 是每個developer該做的事XD，repo應該負責檢查就好，

**Comment by PichuChen** [comment]
關於這次修改的 `oooId` => `oooID` 這邊是相關的討論：
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
https://github.com/golang/lint/issues/124

因此如果沒有其他反對意見的話接下來將會採用 `oooID` 的寫法

**Comment by PichuChen** [comment]
關於這次修改的 http.httpDelivery => http.HttpDelivery => http.Delivery 的部分
主要是避免重覆字串(Stuttering)
相關的規範在 Naming package contents 的 Avoid stutter.
> Avoid stutter. Since client code uses the package name as a prefix when referring to the package contents, the names for  those contents need not repeat the package name. The HTTP server provided by the http package is called Server, not HTTPServer. Client code refers to this type as http.Server, so there is no ambiguity.

https://blog.golang.org/package-names

感謝 @Julian-Chu  提供資料。
