### ISSUE TITLE
[建議] 更新local資料庫並且做測試的script

### ISSUE THREAD

**Issue by tanyeun** [Ptt-official-app/Ptt-backend#40]
### 原本作法的問題 / Existed Problem
這幾天沒事常常就常常試著改一些code然後用curl跑API測試
很多動作重複做覺得很煩

### 實作細節 / Details of Implement
基本上就是把手動做的動作寫成script

./localtest.bash 會做以下幾件事:
1. 詢問要不要更新home
2. 如果要更新，但是已經存在舊的home，要不要保存(會在後面加unix timestamp)
3. 要不要重新build code

./localtest.bash -m auto
就是不問了，直接做掉(幾個問題都當作是yes)

### 期程 / Schedule
已完成

### 相關文件 / Documents
NA

**Comment by PichuChen** [comment]
我知道為什麼你會需要頻繁改 Code了，基本上在測試 Ptt-backend 的時候可以用個假的 go-bbs driver 來提供資料，然後實際上需要使用靜態資料測試的部分可以用 go-bbs 這個套件進行測試開發。

**Comment by tanyeun** [comment]
> 我知道為什麼你會需要頻繁改 Code了，基本上在測試 Ptt-backend 的時候可以用個假的 go-bbs driver 來提供資料，然後實際上需要使用靜態資料測試的部分可以用 go-bbs 這個套件進行測試開發。

還不知道要怎麼使用go-bbs阿

**Comment by PichuChen** [comment]
這個 ISSUE 目前還有在更新嗎？ 不然兩週後要把他先關掉了喔？
