### ISSUE TITLE
[建議] 將 token 部分行為抽出到 middleware, 以後其他類似的 code 也以 middleware 實作

### ISSUE THREAD

**Issue by rainlay** [Ptt-official-app/Ptt-backend#43]
### 原本作法的問題 / Existed Problem
目前許多 API 都會使用到 token CheckPermission or GetUserIdFromToken, 建議可以抽出到為 middleware,
讓 http handler 去重複使用。

### 實作細節 / Details of Implement
將 token 部分 code 抽出至 middleware, 非 API bussiness logic 部分 code 抽成獨立 pkg

### 期程 / Schedule
- 討論時間： 1 ~ 3 天, 到 2/10
- 實作時間： 1 ~ 2 天可完成
- 確認時間： 未定

### 相關文件 / Documents
[mux middleware](https://github.com/gorilla/mux/blob/master/middleware.go)

**Comment by chhsiao1981** [comment]
可參考以下方式 implement:

https://github.com/Ptt-official-app/go-pttbbs/blob/main/api/api_login_required.go
https://github.com/Ptt-official-app/go-pttbbs/blob/main/api/load_general_boards.go

**Comment by PichuChen** [comment]
這個需要另外討論，因為目前在 Token 其實是有權限分級的。
