### ISSUE TITLE
[主線] [PTT] 實作 route_token_test.go

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#45]
### 實作細節 / Details of Implement
請參考 #36 內的討論進行實作。

### 期程 / Schedule
- 討論時間：三天 到 2/12
- 實作時間：一天 到 2/13
- 確認時間：一天 到 2/14

### 相關文件 / Documents
 route_user_test.go

**Comment by TimoChiang** [comment]
我想幫忙！
不過route_token_test.go好像已經在進行中了？(#37)
是要實作其他未動工的部分嗎？
```
route_token_test.go : 使用 mock 完成

route_classes_test.go : 未動工

route_borads_articles_test.go : 未動工

route_borads_test.go : 未動工

route_boards_treasures.go : 未動工
```
---
看完本週影片後，這應該是當作影片範例的子ISSUE的樣子？

**Comment by PHChenGit** [comment]
I can take this too.

**Comment by y2468101216** [comment]
可以先從 route_token_test.go 以外的開始開，先從 #36 裡有列的開始即可。
