### ISSUE TITLE
[主線] [PTT] 實作熱門文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#50]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #107 
- [x] usecase 部分應該是直接將 repository 的結果輸出即可？
  - ISSUE #83 
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。 
  - ISSUE #86 

### 期程 / Schedule
- 討論時間： 一週，到 2/18，可以和實作平行進行。
- 實作時間： 一週，到 2/25
- 確認時間： 一週，到 3/4

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by linmeichu** [comment]
我想寫寫看 `delivery/http` 的部分！

**Comment by PichuChen** [comment]
> 我想寫寫看 `delivery/http` 的部分！

好，那你有辦法參考 https://github.com/Ptt-official-app/Ptt-backend/issues/53 開一個子 ISSUE 然後 ref 到這個 ISSUE 嗎？

**Comment by wagaru** [comment]
想確認一下

所以可以假設 go-bbs 會實作 ReadPopularArticles() 的功能，裡面會回傳可能前 100 篇熱門文章的ArticleRecord
所以 usecase 只要回傳 repository 的資料， 無需做排序的處理？然後現階段應該還先不用使用 cache

是的話我可以幫忙 usecase 的部份~~

**Comment by PichuChen** [comment]
> 想確認一下
> 
> 所以可以假設 go-bbs 會實作 ReadPopularArticles() 的功能，裡面會回傳可能前 100 篇熱門文章的ArticleRecord
> 所以 usecase 只要回傳 repository 的資料， 無需做排序的處理？然後現階段應該還先不用使用 cache

對，理論上應該底層回傳的東西會有進行排序？

> 
> 是的話我可以幫忙 usecase 的部份~~

OK 那你那邊可以開一個子 ISSUE 然後指到這個 ISSUE 嗎？

**Comment by wagaru** [comment]
有個小問題~

照這禮拜投影片的說明，這個母 issue 應該先開出 branch，子 issue 再發 PR 到這個 branch
但目前母 issue 應該是沒人認領開 branch？

**Comment by PichuChen** [comment]
> 有個小問題~
> 
> 照這禮拜投影片的說明，這個母 issue 應該先開出 branch，子 issue 再發 PR 到這個 branch
> 但目前母 issue 應該是沒人認領開 branch？

誒對
