### ISSUE TITLE
[主線] [PTT] 實作熱門看板的看板列表

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#51]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
 - ISSUE #53 
- [x] usecase 部分應該是直接將 repository 的結果輸出即可？
 - ISSUE #164
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。 

### 期程 / Schedule
- 討論時間： 一週，到 2/18，可以和實作平行進行。
- 實作時間： 一週，到 2/25
- 確認時間： 一週，到 3/4

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by nickyanggg** [comment]
我可以試試看這個～

目前實作方式可能會在每次 request 的時候去計算前 100 名的熱門看板，之後再看要不要用 cache

**Comment by PichuChen** [comment]
> 我可以試試看這個～
> 
> 目前實作方式可能會在每次 request 的時候去計算前 100 名的熱門看板，之後再看要不要用 cache

OK

**Comment by PichuChen** [comment]
熱門看板實作方式目前有東西需要討論：

首先在原本的 BBS 系統當中「熱門看板」和「看板列表」是不太一樣的概念，熱門看板並不是單純的「版上人數很多的看板」，他還必須要符合一些條件，例如說他不能是隱藏看板，例如版主版或者是只限定版友進入的個人看板他就不能被列為熱門看板，再來是有些看板他可以設定成不得進入熱門看板等等。

也就是說，熱門看板的列表=篩選條件，可以透過 go-bbs 判斷後回傳，或者是應該透過 usecase 統一判斷熱門看板的商業邏輯後回傳。

因此這邊有兩種可能的實作方式：

1. go-bbs 新增 getPopularBoard 函式，統一判斷熱門看板列表
2. go-bbs 部分統一利用 getBoard 函式回傳，由 Ptt-backend 的 Usecase 透過看板屬性後在 usecase 進行判斷

以上需要請各位提供意見及討論。

**Comment by TimoChiang** [comment]
我自己比較偏好在 Ptt-backend 的 Usecase 處理篩選的邏輯條件～

目前的看板（board）跟分類（class），也是都用在 Usecase 利用 GetBoards 回傳回來的內容再去判斷是哪一種。

另一個原因是在第二週的問題回應中有提到，go-bbs 的定位是 DBMS ー 負責存取結構化的資料的系統。
雖然實作上可能比較輕鬆或處理效率較高，但把有牽涉到商業邏輯的部份放在 go-bbs 感覺不太合適。

順帶提一下，考量到每次在 Ptt-backend 都要拿回全部看板後再判斷的狀況，
以主流 DBMS 的概念去想的話，除了利用 GetBoards 後再一個一個篩選之外，
從 Ptt-backend 發起有邏輯性的篩選條件（例如where is_hidden = 0）感覺也比較合理～
（還沒詳細研究過 go-bbs ，不確定這個例子適不適當or能不能實現）

**Comment by whitefloor** [comment]
#181 repo的issue開好了

#164 #181 這兩個issue麻煩assign給我 感謝

**Comment by PichuChen** [comment]
> #181 repo的issue開好了
> 
> #164 #181 這兩個issue麻煩assign給我 感謝

OK， #164 的部分需要麻煩幫我在下面回應我才能 Assign 喔

**Comment by whitefloor** [comment]
如果照目前的討論方向
#181是不是可以直接close?
我太晚看到了＝＝

**Comment by PichuChen** [comment]
如果要close 的話可以標一下是和那個issue或是pr 重覆了，這樣我可以比較快判斷喔

**Comment by whitefloor** [comment]
> 我自己比較偏好在 Ptt-backend 的 Usecase 處理篩選的邏輯條件～
> 
> 目前的看板（board）跟分類（class），也是都用在 Usecase 利用 GetBoards 回傳回來的內容再去判斷是哪一種。
> 
> 另一個原因是在第二週的問題回應中有提到，go-bbs 的定位是 DBMS ー 負責存取結構化的資料的系統。
> 雖然實作上可能比較輕鬆或處理效率較高，但把有牽涉到商業邏輯的部份放在 go-bbs 感覺不太合適。
> 
> 順帶提一下，考量到每次在 Ptt-backend 都要拿回全部看板後再判斷的狀況，
> 以主流 DBMS 的概念去想的話，除了利用 GetBoards 後再一個一個篩選之外，
> 從 Ptt-backend 發起有邏輯性的篩選條件（例如where is_hidden = 0）感覺也比較合理～
> （還沒詳細研究過 go-bbs ，不確定這個例子適不適當or能不能實現）

照 #51 最後的討論結果
使用GetBoards撈取資料到UseCase判斷
現在已經有GetBoards了
這樣 #181 就不需要實作
