### ISSUE TITLE
[主線] [PTT] 實作個人看板的使用者資訊

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#52]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - 請見 ISSUE #100 
- [x] usecase 部分應該是直接將 repository 的結果輸出即可？
  - 請見 ISSUE #165 
- [x] repository 因為 go-bbs 已經完成了，因此可以直接串接 go-bbs 的相關函式。
  - 請見 ISSUE #58 

### 期程 / Schedule
- 討論時間： 一週，到 2/18，可以和實作平行進行。
- 實作時間： 一週，到 2/25
- 確認時間： 一週，到 3/4

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by fish-dumpling** [comment]
這個我想要幫忙~

**Comment by PichuChen** [comment]
> 這個我想要幫忙~

OK

**Comment by fish-dumpling** [comment]
http和usecase的部分:
1. 看了一下API輸出的結果，除了plan和chess_status缺少子項目之外都是完整的，那部份在go-bbs補齊後應該就會是正確的。目前需要在哪部分把這些先做mock嗎？
2. http的token權限檢查是不是都先跳過呢？或是這支API不需要檢查權限？
3. error message目前看起來是這樣的: 
`		m := map[string]string{
			"error":             "find_userrec_error",
			"error_description": err.Error(),
		}`
參考了board infomation的error_description是這樣的: ` "get board for " + boardId + " failed"`
這部分有需要改或是維持原狀呢？
4. http的testcode可能還需要補齊
5. usecase的部分在repository的子issue就已經解掉了，這邊看起來應該只要確認http還有沒有差什麼需要補的

**Comment by PichuChen** [comment]
> http和usecase的部分:
> 
> 1. 看了一下API輸出的結果，除了plan和chess_status缺少子項目之外都是完整的，那部份在go-bbs補齊後應該就會是正確的。目前需要在哪部分把這些先做mock嗎？

可以先做 mock, 我印象中好像最近 go-bbs 有把他補齊了

> 2. http的token權限檢查是不是都先跳過呢？或是這支API不需要檢查權限？

要檢查權限，實際上應該會因為朋友關係的不同有不同執行結果吧？ (usecase)

> 3. error message目前看起來是這樣的:
>    `		m := map[string]string{ "error":             "find_userrec_error", "error_description": err.Error(), }`
>    參考了board infomation的error_description是這樣的: ` "get board for " + boardId + " failed"`
>    這部分有需要改或是維持原狀呢？

應該是要

> 4. http的testcode可能還需要補齊
> 5. usecase的部分在repository的子issue就已經解掉了，這邊看起來應該只要確認http還有沒有差什麼需要補的

這邊是母 ISSUE, 所以要看還有哪個子 ISSUE 還沒做完，或是發現做完但是有 Bug 這樣。

**Comment by PichuChen** [comment]
@fish-dumpling 可以問一下目前這邊的狀況嗎？

**Comment by fish-dumpling** [comment]
抱歉前幾天太忙，開好http的子issue (#100) 了，usecase目前看起來OK，如果需要修改再開

**Comment by PichuChen** [comment]
@fish-dumpling 問一下 usecase 的子 ISSUE 你那邊會把它開起來嗎？

**Comment by fish-dumpling** [comment]
看起來是要開
