### ISSUE TITLE
[主線] [PTT] 實作熱門看板的看板列表的 http 套件

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#53]
### 實作細節 / Details of Implement
- 參考 #51 實作熱門看板的看板列表
- 在 delivery/http/route_boards.go 裡面新增 getPopularBoardList 內容基本上和 getBoardList 一樣
- 新的函式呼叫 GetPopularBoards  
- 請推入 feature/popular_boards 的 branch

### 期程 / Schedule
- 討論時間： 一天
- 實作時間： 一天
- 確認時間： 一天

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by Julian-Chu** [comment]
在看 #53 的時候發現一個問題，
文件上寫應該是回傳:
```json
{
    "data": {
        "items": [
            {
                "id": {{board_id}},
                "type": {{type}},
                "title": {{title}},
                "number_of_user": {{number_of_user}},
                "moderators": {{moderator_list}},
            }
        ]
    }
}
```
但目前getBoardList跟getPopularBoardList 看起來傳回來的是
```json
{
    "data":  [
            {
                "id": {{board_id}},
                "type": {{type}},
                "title": {{title}},
                "number_of_user": {{number_of_user}},
                "moderators": {{moderator_list}},
            }
        ]
}
```
會少一層item，需要確認一下

**Comment by nickyanggg** [comment]
了解，這樣看來是不是 /v1/boards 也得一起修改？因為目前是照著 /v1/boards 的回傳格式，但文件中 /v1/boards 也有多包一層 items。

如果確定是照著文件的話我晚點馬上修改，謝謝。

**Comment by nickyanggg** [comment]
目前 /v1/popular-boards 已改成文件所要求的回傳格式。

**Comment by PichuChen** [comment]
> 了解，這樣看來是不是 /v1/boards 也得一起修改？因為目前是照著 /v1/boards 的回傳格式，但文件中 /v1/boards 也有多包一層 items。
> 
> 如果確定是照著文件的話我晚點馬上修改，謝謝。

聽起來有可能是 boards 有 Bug, 可能得開 ISSUE 修
