### ISSUE TITLE
[主線] [PTT] 實作 route_borads_test.go

### ISSUE THREAD

**Issue by PHChenGit** [Ptt-official-app/Ptt-backend#55]
### 實作細節 / Details of Implement
實作 #36 內的討論進行實作

### 期程 / Schedule
- 討論時間： 三天
- 實作時間： 兩天
- 確認時間： 兩天

### 相關文件 / Documents
route_boards.go
route_borads_test.go

**Comment by PichuChen** [comment]
@PHChenGit  所以這個 ISSUE 交給你 OK 嗎？

**Comment by PHChenGit** [comment]
> @PHChenGit 所以這個 ISSUE 交給你 OK 嗎？

OK 爹斯

**Comment by PHChenGit** [comment]
不好意思 目前在看 route.go 這隻檔案時有看到
`/v1/boards` 寫了兩次 只差在結尾有沒有 `/`
想請問一下 這樣的目的是為了後面接上子 URI 的部分嗎？
還是單純重複而已？

<img width="732" alt="Screen Shot 2021-02-12 at 11 20 54 PM" src="https://user-images.githubusercontent.com/16322329/107787133-a91b0700-6d89-11eb-880f-4ed3db69fe14.png">

**Comment by PichuChen** [comment]
> 不好意思 目前在看 route.go 這隻檔案時有看到
> `/v1/boards` 寫了兩次 只差在結尾有沒有 `/`
> 想請問一下 這樣的目的是為了後面接上子 URI 的部分嗎？
> 還是單純重複而已？
> 
> <img alt="Screen Shot 2021-02-12 at 11 20 54 PM" width="732" src="https://user-images.githubusercontent.com/16322329/107787133-a91b0700-6d89-11eb-880f-4ed3db69fe14.png">

感覺兩個應該要去到不同的handler function，只是不小心被寫在一起了，Line:11 的應該要分割到名為 `routeBoard` 這個 handler function 去？ 因為他是處理單個看板下的請求。

同樣原因， `routeClasses` 和 `routeUsers` 可能也要改名？

**Comment by PHChenGit** [comment]
> > 不好意思 目前在看 route.go 這隻檔案時有看到
> > `/v1/boards` 寫了兩次 只差在結尾有沒有 `/`
> > 想請問一下 這樣的目的是為了後面接上子 URI 的部分嗎？
> > 還是單純重複而已？
> > <img alt="Screen Shot 2021-02-12 at 11 20 54 PM" width="732" src="https://user-images.githubusercontent.com/16322329/107787133-a91b0700-6d89-11eb-880f-4ed3db69fe14.png">
> 
> 感覺兩個應該要去到不同的handler function，只是不小心被寫在一起了，Line:11 的應該要分割到名為 `routeBoard` 這個 handler function 去？ 因為他是處理單個看板下的請求。

ok 那就另開 issue 解決囉 應該算是 bug?

> 同樣原因， `routeClasses` 和 `routeUsers` 可能也要改名？

這部分我認為應該不用另外改名，原因是裡面的實作是回傳一個 List

**Comment by nickyanggg** [comment]
> 感覺兩個應該要去到不同的handler function，只是不小心被寫在一起了，Line:11 的應該要分割到名為 `routeBoard` 這個 handler function 去？ 因為他是處理單個看板下的請求。

如果需要的話我可以幫忙修這個～

**Comment by PHChenGit** [comment]
這個 Issue 可以 closed 了
