### ISSUE TITLE
[主線] [PTT] 實作個人看板的使用者資訊 (repository)

### ISSUE THREAD

**Issue by fish-dumpling** [Ptt-official-app/Ptt-backend#58]
### 實作細節 / Details of Implement
- #52 的子issue
- branch名稱feature/user_infomation
- 在repository的package中接上go-bbs，回傳UserRecord。
- 這個功能[已有部分實作完成](https://github.com/Ptt-official-app/Ptt-backend/blob/development/internal/repository/user.go#L10) ，但go-bbs未完成的部分在Ptt-backend裡都還沒有實作。

### 期程 / Schedule
- 討論時間： 3天
- 實作時間： 1天
- 確認時間： 1天 

### 相關文件 / Documents
[go-bbs中的UserRecord](https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go#L11)
希望討論一下這個issue有沒有需要先把go-bbs的部分完成後直接接上，根據http文件裡最終需要get的資訊內容看來目前go-bbs裡UserRecord的interface不完整

**Comment by PichuChen** [comment]
如果要做的話可以先把缺的欄位用 Mock 的方式或是回傳假資料然後加上 // TODO 的方式實作，然後等 go-bbs 完成後再把 TODO 拿掉這樣？

**Comment by gn01842919** [comment]
這個我想要試試看!

**Comment by gn01842919** [comment]
想確認一下，`UserRecord` interface 定義在 go-bbs 裡面，我該怎麼 mock 他比較好呢?
是在 `bbs.UserRecord` 外面再包一層 interface 嗎，並把回傳的參數型別改為我新定義的型別沒錯吧?
還是有什麼更漂亮的做法呢? (不好意思我 golang  新手)

**Comment by gn01842919** [comment]
還是這裡的意思只是，`usecase` 當中的 `GetUserInformation` 隨便回些空值就好了呢?

**Comment by PichuChen** [comment]
> 想確認一下，`UserRecord` interface 定義在 go-bbs 裡面，我該怎麼 mock 他比較好呢?
> 是在 `bbs.UserRecord` 外面再包一層 interface 嗎，並把回傳的參數型別改為我新定義的型別沒錯吧?
> 還是有什麼更漂亮的做法呢? (不好意思我 golang 新手)

不需要外面再包一層 interface, 可以參考 `usecase/user_test.go` 裡面 `MockUser` 的作法
