### ISSUE TITLE
[主線] [PTT] 實作個人看板歷史文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#59]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
* http 部分請依照文件實作並且有初步的 testcode。
* usecase 部分應該是直接將 repository 的結果輸出即可。
* repository 部分歷史文章功能應該由 go-bbs 儲存還是 Ptt-backend 掃描後暫存需要討論，暫定由 go-bbs 儲存。

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by whitefloor** [comment]
Hi~我是whitefloor，剛剛有在信件上確認這個問題由我處理

請assign給我，感謝

**Comment by PichuChen** [comment]
@whitefloor 交給你了

**Comment by whitefloor** [comment]
Hi @PichuChen 
我想請問個人看板歷史文章的功能需求是什麼
目前我的理解是可以在個人看板看到自己的歷史文章

另外想請問的是如果我的理解是對的，那這部分會有權限控管嗎？
例如黑名單無法看見你的歷史文章

**Comment by PichuChen** [comment]
@whitefloor 

對，基本上是比照目前其他平台做的。
權限管控的部分基本上只顯示公開看板的發文。

**Comment by whitefloor** [comment]
好的，那我照/v1/users/{{user_id}}/articles的相關敘述下去實作。

進度的話我先從delivery開始下手
usecase ＆repository在我做完前期待有人加入討論XD

**Comment by xboxa5105** [comment]
@whitefloor 我可以一起幫忙這個issue

**Comment by whitefloor** [comment]
@xboxa5105 感謝

目前usercase和delivery沒有問題
主要問題是出在repository上，需要對這部分討論
因為go-bbs還沒實作出來getUserArticles，data暫定由go-bbs儲存的話
那這部分一樣先做mock就好嗎？
還是說連同go-bbs的部分與這個issueu連動一起處理，這樣就不需要做mock

**Comment by whitefloor** [comment]
整理一下討論過後的預計做法跟進度

1.ptt-backend的repository需要go-bbs解析，但go-bbs尚未實作
2.決定與go-bbs一起實作，這樣在ptt-backend就不需要做mock
3.在go-bbs實作時需要開issue
4.ptt-backend串接go-bbs時需要在go.mod增加版本號碼0.2.5 > 0.2.6

但go-bbs那邊我還沒碰過，要花點時間看怎麼處理

**Comment by PichuChen** [comment]
go-bbs 應該已經有 getBoardList 和 getArticles 了，所以用這兩組應該就行了？
