### ISSUE TITLE
CI / CD 檔案建立

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#6]
突然發現這個專案好像還沒有設定 CI / CD ?

**Comment by mkfsn** [comment]
@PichuChen 有什麼選項嗎？目前我知道的有：

1. [CircleCI](https://circleci.com/)
2. [GithubCI](https://docs.github.com/en/actions)
3. [TravisCI](https://travis-ci.org/)

如果 CI 確定的話我也想要導入 https://github.com/golangci/golangci-lint

**Comment by PichuChen** [comment]
沒意外應該是 GitHub?

**Comment by Julian-Chu** [comment]
assign給我吧(ps: slack裡面認領了)
我應該會先弄makefile command
然後CI直接call makefile

個人贊成 @mkfsn  引入linter的意見， 可以一併在這個issue處理

**Comment by Julian-Chu** [comment]
目前跑出來的CI流程結果可以在這看到 [link](https://github.com/Julian-Chu/Ptt-backend/actions)

目前linter掃出一些問題所以紅燈， 等review流程完在修正

**Comment by PichuChen** [comment]
目前的 CI 好像沒辦法在 macOS 上面執行？ 他會查不到 go bin

**Comment by Julian-Chu** [comment]
> 目前的 CI 好像沒辦法在 macOS 上面執行？ 他會查不到 go bin

有error log嗎， 我看一下， 手邊沒有mac不能測
順便幫我確認一下 gobin是不是有設定了

**Comment by PichuChen** [comment]
> > 目前的 CI 好像沒辦法在 macOS 上面執行？ 他會查不到 go bin
> 
> 有error log嗎， 我看一下， 手邊沒有mac不能測
> 順便幫我確認一下 gobin是不是有設定了

預設應該是沒有設定

**Comment by PichuChen** [comment]
@Julian-Chu 這邊是輸出的 log
```
$ ./make.bash lint
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.36.0 for v1.36.0/darwin/amd64
install: mkdir : No such file or directory
download golangci-lint into
golangci-lint checking...
./make.bash: line 49: /golangci-lint: No such file or directory
```

可能要考慮開發者沒有設定 gobin 時應該要怎麼給預設值的問題。
FYI
```
$ go env GOBIN

```

**Comment by Julian-Chu** [comment]
#46  把GOBIN改成 GOPATH/bin ，GOPATH應該就不會有沒設定的問題了
