### ISSUE TITLE
[主線] [PTT] 實作個人看板歷史留言

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#60]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #160
- [x] usecase 部分應該是直接將 repository 的結果輸出即可。
  - ISSUE #161
- [x] repository 部分歷史留言功能應該由 go-bbs 儲存還是 Ptt-backend 掃描後暫存需要討論，暫定由 go-bbs 儲存。
  - ISSUE #162

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by PichuChen** [comment]
@TimoChiang

**Comment by TimoChiang** [comment]
👋

**Comment by PichuChen** [comment]
> 👋

再麻煩請你幫忙找人和開立子 ISSUE 了

**Comment by TimoChiang** [comment]
需要有人幫忙實作，有興趣的人可以留言哦！

**Comment by SivWatt** [comment]
今天會幫忙開立子ISSUE～

**Comment by PichuChen** [comment]
三個子 ISSUE 都完成了，接下來需要另外再驗證行為是否正確。
