### ISSUE TITLE
[主線] [PTT] 實作儲存草稿

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#61]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #166
- [x] usecase 部分應該是直接將 repository 的結果輸出即可。
  - ISSUE #168
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。
  - ISSUE #167
  
### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by PichuChen** [comment]
@TimoChiang

**Comment by TimoChiang** [comment]
👋

**Comment by PichuChen** [comment]
> 👋


再麻煩請你幫忙找人和開立子 ISSUE 了

**Comment by TimoChiang** [comment]
需要有人幫忙實作，有興趣的人可以留言哦！

**Comment by linmeichu** [comment]
我可以幫忙！🖖

**Comment by TimoChiang** [comment]
@linmeichu OK～
你要試試看`repository`這塊嗎？應該比`delivery/http` `usecase` 稍微難一些些

**Comment by PichuChen** [comment]
@TimoChiang  問一下這個 ISSUE 的三個子 ISSUE 有開出來了嗎？

**Comment by linmeichu** [comment]
> @linmeichu OK～
> 你要試試看`repository`這塊嗎？應該比`delivery/http` `usecase` 稍微難一些些

欸欸好～
