### ISSUE TITLE
[主線] [PTT] 實作使用者設定

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#62]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #118
- [x] usecase 部分應該是直接將 repository 的結果輸出即可。
  - ISSUE #148
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。
  - ISSUE #148

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by kyho4515** [comment]
我想試試看這部分, 請指派給我

**Comment by PichuChen** [comment]
> 我想試試看這部分, 請指派給我

OK，那在麻煩你幫忙開立相關的子ISSUE

**Comment by kyho4515** [comment]
這部分我想是都完成了
另外, 目前users的部分好像都還沒做post, 這是之後再開其他issue處理嗎?

**Comment by PichuChen** [comment]
有也可能是排入milestone 2
