### ISSUE TITLE
[主線] [PTT] 實作顯示發文限制

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#63]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #126
- [x] usecase 部分應該是直接將 repository 的結果輸出即可。
  - ISSUE #126
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。
  - ISSUE #116 

### 期程 / Schedule
- 討論時間： 一週, 到 3/9
- 實作時間： 一週, 到 3/16
- 確認時間： 一週, 到 3/23

注意這個 endpoint 是 `/v1/boards/{{board_id}}/information`

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by wagaru** [comment]
文件上看起來發文限制跟看板資訊(#65)應該是同一個 endpoint ，這樣還要拆成二個 issue 嗎？

[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1g6ovfezg1)

**Comment by PichuChen** [comment]
> 文件上看起來發文限制跟看板資訊(#65)應該是同一個 endpoint ，這樣還要拆成二個 issue 嗎？
> 
> [PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1g6ovfezg1)

剛剛確認過是不一樣的， #65 指的是「細部資訊」 是 `/v1/boards/{{board_id}}/settings` ，這個是 `/v1/boards/{{board_id}}/information` 因此是不同 endpoint

**Comment by wagaru** [comment]
這邊先假設 go-bbs 的 BoardRecord 會提供相關發文限制資訊 (已開 [ISSUE](https://github.com/Ptt-official-app/go-bbs/issues/61))

**Comment by wagaru** [comment]
usecase 的部份印象中 #127 應該是一起做掉了？

**Comment by PichuChen** [comment]
> usecase 的部份印象中 #127 應該是一起做掉了？

看來是
