### ISSUE TITLE
[主線] [PTT] 實作顯示看板發文資訊

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#64]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
* http 部分請依照文件實作並且有初步的 testcode。
* usecase 部分應該是直接將 repository 的結果輸出即可。
* repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by nickyanggg** [comment]
請問這是對應到 [PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx) 中的哪個 endpoint ?

**Comment by RicoToothless** [comment]
有收到指派了感謝，也有意願做，
但目前暫定 4/15 之後才比較有空深入研究，撇人新手請多多指教。

**Comment by PichuChen** [comment]
> 有收到指派了感謝，也有意願做，
> 但目前暫定 4/15 之後才比較有空深入研究，撇人新手請多多指教。
感謝回應～
兩週有比較久，那這之中我在看一下有沒有其他人能幫忙好了。

**Comment by PichuChen** [comment]
> 請問這是對應到 [PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.aapnwrfqwltx) 中的哪個 endpoint ?

應該是 /v1/boards/{{board_id}}/information ? 從一開始的需求看起來是要讓前端發文前檢查使用者有沒有發文權限用的

**Comment by nickyanggg** [comment]
> 應該是 /v1/boards/{{board_id}}/information ? 從一開始的需求看起來是要讓前端發文前檢查使用者有沒有發文權限用的

/v1/boards/{{board_id}}/information 貌似已經在這個 issue #63 被實作過了？

**Comment by PichuChen** [comment]
> > 應該是 /v1/boards/{{board_id}}/information ? 從一開始的需求看起來是要讓前端發文前檢查使用者有沒有發文權限用的
> 
> /v1/boards/{{board_id}}/information 貌似已經在這個 issue #63 被實作過了？

Duplicate of #63
