### ISSUE TITLE
[主線] [PTT] 實作顯示看板資訊細部資訊

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#65]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #137
- [ ] usecase 部分應該是直接將 repository 的結果輸出即可。
- [ ] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。

注意這個 ISSUE 指的是「細部資訊」  `/v1/boards/{{board_id}}/settings`
### 期程 / Schedule
- 討論時間： 一週, 到 3/9
- 實作時間： 一週, 到 3/16
- 確認時間： 一週, 到 3/23

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by gn01842919** [comment]
我想做做看 http 的部分

**Comment by gn01842919** [comment]
這個的 http 部分是不是已經有了? 只是缺 test 而已?

**Comment by gn01842919** [comment]
我來試試看 repository 的部分好了

**Comment by PichuChen** [comment]
> 這個的 http 部分是不是已經有了? 只是缺 test 而已?

你是說 Delivery 部分嗎？

**Comment by gn01842919** [comment]
對，"http 部分請依照文件實作並且有初步的 testcode。"，我看 delivery/http 看起來有相關的程式碼了?

**Comment by PichuChen** [comment]
> 對，"http 部分請依照文件實作並且有初步的 testcode。"，我看 delivery/http 看起來有相關的程式碼了?

哪有可能是之前有做好了不過我沒有登記到，不然就是要再檢查看看有沒有有漏的這樣...

**Comment by nickyanggg** [comment]
我可以幫忙這個～

**Comment by PichuChen** [comment]
@nickyanggg 再麻煩你了

**Comment by PichuChen** [comment]
usecase 和 repo 看起來用既有的就完成了，因此 close
