### ISSUE TITLE
[主線] [PTT] 實作轉錄看板文章

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#66]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #152
- [x] usecase 部分應該要檢查目前使用者有沒有在該版發文權限以及檢查轉錄文章相關權限
  - ISSUE #153
- [ ] ~~repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。~~
  - ~~ISSUE #154~~
  - 因為repository 應該是直接串接原有發文及推文的就行了，因此先刪掉
  

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by arhtur007** [comment]
已另外開設三個子issue

**Comment by PichuChen** [comment]
> 已另外開設三個子issue

不好意思，可以幫忙補充一下需要修改的檔案位置嗎？

**Comment by arhtur007** [comment]
阿啊不好意思～

我回家之後研究一下！
Pichu Chen ***@***.***>於 2021年4月2日 週五，20:57寫道：
