### ISSUE TITLE
[主線] [PTT] 實作轉錄信箱

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#67]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
  - ISSUE #155
- [x] usecase 部分應該要檢查目前使用者有沒有轉錄信箱相關權限。
  - ISSUE #156 
- [x] Email 寄送服務的 Provider #191   
- [ ] ~~repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。~~
  - 看起來應該是讀取原有文章後改用 Email 的 provider 就可以處理了，因此不需要另外再處理 repository
  - ~~ISSUE #157~~

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by titaneric** [comment]
已協助開設對應子issue

**Comment by PichuChen** [comment]
> 已協助開設對應子issue

子ISSUE的部分可以幫忙補充一下要修改的檔案嗎？

**Comment by titaneric** [comment]
sorry,假日可以來處理
專案部份我有點陌生，自己要先看過一次，再找出會修改的檔案

**Comment by titaneric** [comment]
@PichuChen 已補上，有誤再請指正

**Comment by PichuChen** [comment]
轉入信箱的部分應該還需要一個提供寄信功能的 Provider
