### ISSUE TITLE
[主線] [PTT] 實作文章推文

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-backend#68]
### 實作細節 / Details of Implement
根據目前架構，應該分成 `delivery/http` `usecase` `repository` 三個子 ISSUE 下去實作。
- [x] http 部分請依照文件實作並且有初步的 testcode。
 - ISSUE #115 
- [x] usecase 部分應該要檢查目前使用者有沒有在該版發文權限以及該版是否禁止推文。
 - ISSUE #147 
- [x] repository 因為 go-bbs 可能還沒完成，因此需要先 mock 一個暫時性的結果等待 go-bbs 完成之後進行串接。
 - ISSUE #194

### 期程 / Schedule
- 討論時間： 一週, 到 2/20
- 實作時間： 一週, 到 2/27
- 確認時間： 一週, 到 3/5

### 相關文件 / Documents
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k)

**Comment by DeanXu2357** [comment]
請指派給我

**Comment by DeanXu2357** [comment]
我想幫忙，請指派給我

**Comment by gogog22510** [comment]
我可以幫忙repo部分
