### ISSUE TITLE
[主線] [PTT] 實作 route_boards_treasures_test.go

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#73]
實作細節 / Details of Implement
實作 #36 內的討論進行實作

期程 / Schedule
討論時間： 三天
實作時間： 一天
確認時間：  一天

相關文件 / Documents
route_boards_treasures.go
route_boards_treasures_test.go

備註:
pr 請指向 development_enable_lint branch

**Comment by kdkaydai** [comment]
我願意試試看

**Comment by PichuChen** [comment]
@kdkaydai  想問一下這邊進度到哪邊了？

**Comment by kdkaydai** [comment]
我還在研究階段

**Comment by techeternalriverco** [comment]
換我接手此 issue 。

**Comment by y2468101216** [comment]
完成了 close
