### ISSUE TITLE
[主線] [PTT] 實作 route_borads_articles_test.go

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#74]
實作細節 / Details of Implement
實作 #36 內的討論進行實作

期程 / Schedule
討論時間： 三天
實作時間： 一天
確認時間： 一天

相關文件 / Documents
route_borads_articles.go
route_borads_articles_test.go

備註:
pr 請指向 development_enable_lint branch

**Comment by DeanXu2357** [comment]
我願意幫忙
