### ISSUE TITLE
[建議] PR 切換 Target branch 時應該可以考慮重新跑一次 CI

### ISSUE THREAD

**Issue by PHChenGit** [Ptt-official-app/Ptt-backend#77]
### 原本作法的問題 / Existed Problem
原本的做法是假設一開始的 target branch 是 development 那麼推 code 上去時會跑一次 development CI 這部分沒有問題
但如果中途切到其他 branch 例如 development_enable_lint 那麼 development_enable_lint CI 目前好像就不會跑 除非再推一個 commit 上來

### 實作細節 / Details of Implement
應該是改 github action ？

**Comment by PichuChen** [comment]
GitHub Action 好像都是有 push 的時候才會跑 CI ，目前設定是 push / Pull Request 的時候跑
https://github.com/Ptt-official-app/Ptt-backend/blob/250a656d47131d7d17039d9b45612b524a18500c/.github/workflows/go.yaml#L3

**Comment by NickLi0627** [comment]
剛剛查了一下, 應該是可以在`on`中新增`pull_requests`, 並且在`pull_request`中新增`edit` type
理論上應該也是會trigger一次CI
[Ref](https://github.community/t/rerun-on-base-branch-change/115594/2)

**Comment by PHChenGit** [comment]
我可以協助這個項目

**Comment by PichuChen** [comment]
雖然還不是很確定是要處理什麼問題，不過先Assign 給你了

**Comment by RicoToothless** [comment]
我是比較建議用 comment trigger 比較直覺，比 `pull_request` `edit` type 來的通用一點，
因為有可能這次 CICD 沒過只是單純 GitHub Action server 有點問題，或是有些 package-management server 有問題，純粹發個特定的 comment 來 trigger CICD workflow 比較好一點。
我也可以幫忙這個 issue，
預計會試試看這個 [GitHub Action](https://github.com/Khan/pull-request-comment-trigger)。

**Comment by PichuChen** [comment]
> 我是比較建議用 comment trigger 比較直覺，比 `pull_request` `edit` type 來的通用一點，
> 因為有可能這次 CICD 沒過只是單純 GitHub Action server 有點問題，或是有些 package-management server 有問題，純粹發個特定的 comment 來 trigger CICD workflow 比較好一點。
> 我也可以幫忙這個 issue，
> 預計會試試看這個 [GitHub Action](https://github.com/Khan/pull-request-comment-trigger)。

Comment trigger 也可以，不過其實在 Slack 留言的話我看到也會手動按重跑

**Comment by RicoToothless** [comment]
我研究了一下發現，因為 GitHub Actions 對 `issue_comment` trigger 非常簡單，只有 `created` `edited` `deleted`（[參考](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment)）
現階段有兩個問題：
1. 他只會 trigger default branch 上的 workflows file（很詭異的機制，實測的時候有踩到，文件也有寫）

2. 目前我看到的 GitHub Actions plugin 都是以 `issue_comment` `created` 去實作，
就會有個問題就是一定得先 trigger 後 plugins 才能做 comment 內容的判斷，
所以單純的討論也會 trigger 一大堆的 GitHub Actions。

**Comment by PHChenGit** [comment]
單純的討論也會嗎？
之前似乎沒注意到...

**Comment by RicoToothless** [comment]
> 單純的討論也會嗎？
> 之前似乎沒注意到...

之前是什麼時候？
 
另外，我看了一下 `pull_request` [event type](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request)
default 有 `opened` `synchronize` `reopened` 都會 trigger CICD workflow
或許單純的 `reopened` 就可以解決你的問題了？（已測試過 `reopened` 可以運作）
