### ISSUE TITLE
[主線] [PTT] 實作熱門文章的 usecase 套件

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/Ptt-backend#83]
### 實作細節 / Details of Implement
* 參考 #50 實作熱門文章
* 在 usecase/board.go 裡面新增 GetPopularArticles()
* 新的函式呼叫 GetPopularArticles
* 請推入 feature/popular_articles

### 期程 / Schedule
- 討論時間： 一天
- 實作時間： 一天
- 確認時間： 一天

### 相關文件 / Documents
[PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1ehnllv3ris)

因為這邊會呼叫到 repository 裡的 GetPopularArticles()，但 repository 不在這個 issue 的範圍，這樣我可以在 repository.go 裡把 interface 開起來嗎？還是有更好的做法

**Comment by gn01842919** [comment]
請讓我試試看

**Comment by PichuChen** [comment]
@gn01842919 這個 ISSUE 是 @wagaru 在 #53 認領的

**Comment by PichuChen** [comment]
> 因為這邊會呼叫到 repository 裡的 GetPopularArticles()，但 repository 不在這個 issue 的範圍，這樣我可以在 repository.go 裡把 interface 開起來嗎？還是有更好的做法

預定的 interface 名稱會叫什麼呢？

**Comment by gn01842919** [comment]
了解，不好意思

**Comment by wagaru** [comment]
> 了解，不好意思

這個主線 #50 還有一個 repository 目前應該是還沒人認領？
如果 @gn01842919 願意的話，這張就交給 @gn01842919，我改去做 repository 呢？

**Comment by gn01842919** [comment]
其實我只是想找個事做，因為之前會開 subissue 出來讓人認領，有點誤會了
不然我去做 repository 的部分好了?
