### ISSUE TITLE
[建議] errcheck 是否有必要

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#93]
### 相關 issue
- #90 

### 原本作法的問題 / Existed Problem
以目前 ci 的狀況看起來 errcheck fail 為大宗，目前看起來都是在 call io 相關沒有檢查 bytes 是否不為0 

### 實作細節 / Details of Implement
增加 golangci.yaml 移除 io 相關 errcheck

### 期程 / Schedule
無

### 相關文件 / Documents
https://golangci-lint.run/usage/configuration/

**Comment by PichuChen** [comment]
目前因為 errcheck 的錯誤數量大概有多少？

**Comment by Julian-Chu** [comment]
https://github.com/Ptt-official-app/Ptt-backend/pull/42#discussion_r577690083
附上跟 @mkfsn  的討論，
production code的errcheck是必要的， 唯一可以商榷的就是test code的部分

目前的errcheck錯誤的數量是頂多一兩個小時就可以修復的範圍，並不是個disable errcheck的好理由
#42 有針對目前lint發現的各種問題有提出暫時的修正方式

**Comment by rainlay** [comment]
> 
> 
> [#42 (comment)](https://github.com/Ptt-official-app/Ptt-backend/pull/42#discussion_r577690083)
> 附上跟 @mkfsn 的討論，
> production code的errcheck是必要的， 唯一可以商榷的就是test code的部分
> 
> 目前的errcheck錯誤的數量是頂多一兩個小時就可以修復的範圍，並不是個disable errcheck的好理由
> #42 有針對目前lint發現的各種問題有提出暫時的修正方式

贊同採用 _ = 進行處理暫時不確定是否要 handle 的 error

**Comment by y2468101216** [comment]
我沒說要全關，主要只關 io 相關部份(ex : responsewriter)的，我看官方文件跟其他專案也不會特別處理 io 相關的。

**Comment by PichuChen** [comment]
> 我沒說要全關，主要只關 io 相關部份(ex : responsewriter)的，我看官方文件跟其他專案也不會特別處理 io 相關的。

有範例和截圖幫忙說明例如哪一行的警告嗎？

**Comment by kiraxie** [comment]
我認為全部 error 全部都要處理比較安全合理，即使是 unit test 也最好是一一確認每個 error case 是否如預期

**Comment by y2468101216** [comment]
```
internal/delivery/http/route_boards.go:22:11: Error return value of `w.Write` is not checked (errcheck)
w.Write([]byte(`{"error":"token_invalid"}`))
```
以官方文件來說:
https://golang.org/pkg/io/#WriteString

他其實也不會特別處理 io 問題。
我不會特別去驗證官方的 io 相關傳回來的 byte 是否正確，因為我也不知道如何驗證他傳回來的 byte。

**Comment by Julian-Chu** [comment]
> ```
> internal/delivery/http/route_boards.go:22:11: Error return value of `w.Write` is not checked (errcheck)
> w.Write([]byte(`{"error":"token_invalid"}`))
> ```
> 
> 以官方文件來說:
> https://golang.org/pkg/io/#WriteString
> 
> 他其實也不會特別處理 io 問題。
> 我不會特別去驗證官方的 io 相關傳回來的 byte 是否正確，因為我也不知道如何驗證他傳回來的 byte。

測試上為了簡單偶爾會忽略這個檢查 或是確認writer不會回傳err就可以不用檢查
別的官方文件有加註忽略的理由
https://golang.org/pkg/fmt/#Sprintf
production code 都會檢查，以response為例
https://golang.org/src/net/http/response.go#317
![image](https://user-images.githubusercontent.com/7224544/108898468-86a1ad00-7617-11eb-8f2f-84e6d8a48d67.png)


byte多半用做writer內部檢查，正常情況的確不會用到

**Comment by y2468101216** [comment]
目前看起來 io 部分只要有回傳 byte lint 就一定要你檢查，就算你有檢查 err 也是一樣

**Comment by y2468101216** [comment]
目前看起來 errcheck 只要有回傳 byte 就會強迫你檢查，我是覺得不必

**Comment by PichuChen** [comment]
> ```
> internal/delivery/http/route_boards.go:22:11: Error return value of `w.Write` is not checked (errcheck)
> w.Write([]byte(`{"error":"token_invalid"}`))
> ```
> 
> 以官方文件來說:
> https://golang.org/pkg/io/#WriteString
> 
> 他其實也不會特別處理 io 問題。
> 我不會特別去驗證官方的 io 相關傳回來的 byte 是否正確，因為我也不知道如何驗證他傳回來的 byte。

我認為以 Example 的寫法來作為最佳實作的依據是不可靠的，因為 Example 在寫作時應該會以簡潔扼要為主，對於 Example 的程式碼也不會有測試案例，因此不檢查錯誤也是有可能的。

我認為可以參考的是實際上的 io 套件的原始碼
https://golang.org/src/io/io.go

在 Line:423 的部分確實有提供 Read 以及 Write 在進行錯誤處理的實務上是如何進行的範例
```
		nr, er := src.Read(buf)
		if nr > 0 {
			nw, ew := dst.Write(buf[0:nr])
			if nw < 0 || nr < nw {
				nw = 0
				if ew == nil {
					ew = errInvalidWrite
				}
			}
			written += int64(nw)
			if ew != nil {
				err = ew
				break
			}
			if nr != nw {
				err = ErrShortWrite
				break
			}
		}
		if er != nil {
			if er != EOF {
				err = er
			}
			break
		}
		
```

**Comment by y2468101216** [comment]
看來是應該要處理，那我先增加 byte 是否為0的檢查跟是否有 err 的檢查

**Comment by Julian-Chu** [comment]
> > ```
> > internal/delivery/http/route_boards.go:22:11: Error return value of `w.Write` is not checked (errcheck)
> > w.Write([]byte(`{"error":"token_invalid"}`))
> > ```
> > 
> > 
> > 以官方文件來說:
> > https://golang.org/pkg/io/#WriteString
> > 他其實也不會特別處理 io 問題。
> > 我不會特別去驗證官方的 io 相關傳回來的 byte 是否正確，因為我也不知道如何驗證他傳回來的 byte。
> 
> 我認為以 Example 的寫法來作為最佳實作的依據是不可靠的，因為 Example 在寫作時應該會以簡潔扼要為主，對於 Example 的程式碼也不會有測試案例，因此不檢查錯誤也是有可能的。
> 
> 我認為可以參考的是實際上的 io 套件的原始碼
> https://golang.org/src/io/io.go
> 
> 在 Line:423 的部分確實有提供 Read 以及 Write 在進行錯誤處理的實務上是如何進行的範例
> 
> ```
> 		nr, er := src.Read(buf)
> 		if nr > 0 {
> 			nw, ew := dst.Write(buf[0:nr])
> 			if nw < 0 || nr < nw {
> 				nw = 0
> 				if ew == nil {
> 					ew = errInvalidWrite
> 				}
> 			}
> 			written += int64(nw)
> 			if ew != nil {
> 				err = ew
> 				break
> 			}
> 			if nr != nw {
> 				err = ErrShortWrite
> 				break
> 			}
> 		}
> 		if er != nil {
> 			if er != EOF {
> 				err = er
> 			}
> 			break
> 		}
> 		
> ```

補充一點，一般使用不需要檢查byte長度，pichu這個範例是因為需要利用byte長度比對判斷後回傳特定的error
在Writer的interface上有說明了，傳入跟傳出的長度不同會拋出錯誤

![image](https://user-images.githubusercontent.com/7224544/108962823-97830a80-7679-11eb-9ced-56899386a9ec.png)

**Comment by y2468101216** [comment]
沒注意到，感謝

**Comment by y2468101216** [comment]
定案決定要全部處理
