### ISSUE TITLE
[主線] [PTT] 移除沒有用到的 delivery.getClass 以及 delivery.routeClass

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/Ptt-backend#94]
相關 issue
#90

原本作法的問題 / Existed Problem
目前 ci 顯示有無用的函數，需要移除並測試是否不影響原本的程式碼

實作細節 / Details of Implement
1. 移除 internal\delivery\http\route_classes.go 裡的 func `(*httpDelivery).getClass` 
2. 移除 internal\delivery\http\route.go 裡的 func `(*httpDelivery).routeClass` 

期程 / Schedule
討論時間 : 一天
實作時間 : 一天
確認時間 : 一天

備註:
請參考 FOR_TEST_DEVELOPERS.md 發 pr

**Comment by PichuChen** [comment]
這個應該不是發到 enable_lint branch?
